-- Every database function the browser calls must exist and be executable by the role that calls it.
-- Generated by scripts/generate-rpc-grant-test.mjs from the supabase.rpc() calls in src/ (do not edit by hand;
-- run `node scripts/generate-rpc-grant-test.mjs` after adding an RPC call). verify:sql-runtime-safety fails if
-- this list drifts from the source.
--
-- Why it matters: a migration that REVOKEs EXECUTE (hardening) while the app still calls the function makes
-- the feature fail in production with "permission denied for function", which static checks cannot see.
BEGIN;

SELECT '1..1';

CREATE TEMP TABLE browser_rpc_names (name text PRIMARY KEY) ON COMMIT DROP;
INSERT INTO browser_rpc_names (name) VALUES
  ('add_invoice_item_transaction'),
  ('add_project_cost_entry'),
  ('add_purchase_order_item'),
  ('adjust_product_stock'),
  ('advance_delivery_in_transit'),
  ('allocate_installation_material'),
  ('assign_delivery_driver'),
  ('assign_installation_staff'),
  ('cancel_communication_outbox'),
  ('check_order_fulfillment_readiness'),
  ('complete_data_subject_request'),
  ('complete_maintenance_visit_360'),
  ('complete_order_delivery'),
  ('create_business_continuity_plan'),
  ('create_data_governance_policy'),
  ('create_data_subject_request'),
  ('create_hse_corrective_action_360'),
  ('create_hse_site_control_360'),
  ('create_hse_site_event_360'),
  ('create_invoice_transaction'),
  ('create_maintenance_plan_360'),
  ('create_operational_incident'),
  ('create_order_delivery'),
  ('create_product_admin'),
  ('create_project_issue'),
  ('create_project_task'),
  ('create_purchase_order'),
  ('create_secure_customer_order'),
  ('create_service_case'),
  ('create_supplier'),
  ('delete_draft_invoice_transaction'),
  ('delete_product_admin'),
  ('delete_project_cost_entry'),
  ('dispatch_order_delivery'),
  ('fail_order_delivery'),
  ('get_active_delivery_drivers'),
  ('get_automation_operations_360'),
  ('get_business_analytics'),
  ('get_business_continuity_360'),
  ('get_commercial_lifecycle_360'),
  ('get_communication_conversations_360'),
  ('get_communication_operations_summary'),
  ('get_communications_center_360'),
  ('get_communications_customer_journey_360'),
  ('get_current_staff_permissions'),
  ('get_current_staff_profile'),
  ('get_customer_communications_self_service_360'),
  ('get_customer_journey'),
  ('get_customer_lifecycle_360'),
  ('get_customer_lifecycle_operations_360'),
  ('get_customer_maintenance_plans_360'),
  ('get_customer_payment_methods'),
  ('get_customer_portal_360'),
  ('get_customer_portal_data'),
  ('get_customer_portal_documents'),
  ('get_customer_portal_preferences'),
  ('get_customer_renewal_history_360'),
  ('get_customer_renewal_operations_360'),
  ('get_data_governance_360'),
  ('get_executive_operations_360'),
  ('get_finance_control_360'),
  ('get_finance_operations_360'),
  ('get_fulfillment_delivery_360'),
  ('get_hse_site_compliance_360'),
  ('get_installation_operations_360'),
  ('get_inventory_procurement_operations_360'),
  ('get_maintenance_operations_360'),
  ('get_order_operations_360'),
  ('get_project_delivery_360'),
  ('get_public_site_content'),
  ('get_published_site_page'),
  ('get_reliability_operations_360'),
  ('get_reporting_operational_intelligence_360'),
  ('get_service_case_operations_360'),
  ('get_service_case_quality_360'),
  ('get_supply_chain_360'),
  ('get_system_health_snapshot'),
  ('get_theme_brand_governance_360'),
  ('mark_all_notifications_read'),
  ('mark_delivery_picked'),
  ('mark_notification_read'),
  ('mark_order_ready_for_fulfillment'),
  ('queue_communication_conversation_reply'),
  ('queue_customer_message'),
  ('receive_purchase_order_item'),
  ('reconcile_communications_360'),
  ('reconcile_customer_lifecycle_360'),
  ('reconcile_executive_operations_360'),
  ('reconcile_finance_control_360'),
  ('reconcile_inventory_procurement'),
  ('reconcile_order_payment_totals'),
  ('reconcile_payment_attempt_360'),
  ('reconcile_project_delivery_360'),
  ('reconcile_service_case_slas_360'),
  ('reconcile_supply_chain_360'),
  ('record_access_review'),
  ('record_delivery_exception'),
  ('record_installation_measurement'),
  ('record_installation_progress'),
  ('record_invoice_payment_transaction'),
  ('record_payment_provider_certification_360'),
  ('record_project_measurement'),
  ('record_project_quality_inspection'),
  ('record_recovery_checkpoint'),
  ('record_recovery_drill'),
  ('recover_failed_delivery'),
  ('refresh_customer_renewal_opportunities_360'),
  ('refresh_invoice_lifecycle_statuses'),
  ('refresh_service_case_warranty_360'),
  ('remove_installation_assignment'),
  ('remove_invoice_item_transaction'),
  ('remove_purchase_order_item'),
  ('report_installation_issue'),
  ('reschedule_order_delivery'),
  ('resolve_installation_issue'),
  ('resolve_inventory_alert'),
  ('retry_communication_outbox'),
  ('rollback_theme_brand_version'),
  ('save_payment_gateway_control_360'),
  ('save_site_page_block'),
  ('save_theme_brand_version'),
  ('schedule_maintenance_visit_360'),
  ('set_primary_product_image'),
  ('set_warehouse_stock'),
  ('signoff_installation'),
  ('submit_quotation_request'),
  ('submit_service_case_feedback'),
  ('track_order_public'),
  ('transfer_stock'),
  ('transition_customer_renewal_360'),
  ('transition_invoice_lifecycle'),
  ('transition_maintenance_plan_360'),
  ('transition_purchase_order_lifecycle'),
  ('transition_quotation_status'),
  ('transition_service_case_360'),
  ('update_communication_conversation_360'),
  ('update_customer_notification_preferences'),
  ('update_delivery_dispatch'),
  ('update_hse_corrective_action_360'),
  ('update_hse_event_360'),
  ('update_installation_material_allocation'),
  ('update_installation_status'),
  ('update_operational_incident'),
  ('update_order_status_transaction'),
  ('update_product_admin'),
  ('update_project_cost_entry'),
  ('update_project_delivery_status'),
  ('update_service_case'),
  ('update_supplier'),
  ('validate_coupon');

SELECT CASE
  WHEN count(*) = 0 THEN 'ok 1 - every browser RPC exists and is executable by anon or authenticated'
  ELSE 'not ok 1 - browser RPCs missing or not executable by anon/authenticated'
END
FROM (
  SELECT b.name FROM browser_rpc_names b
  WHERE NOT EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = b.name
      AND (has_function_privilege('anon', p.oid, 'execute') OR has_function_privilege('authenticated', p.oid, 'execute'))
  )
) missing;

SELECT '# ' || b.name || ': no overload is executable by anon or authenticated (or the function does not exist)'
FROM browser_rpc_names b
WHERE NOT EXISTS (
  SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
  WHERE n.nspname = 'public' AND p.proname = b.name
    AND (has_function_privilege('anon', p.oid, 'execute') OR has_function_privilege('authenticated', p.oid, 'execute'))
)
ORDER BY b.name;

ROLLBACK;
