import { supabase } from '@/lib/supabase';

export type ContinuityPlan = { id:string; domain:string; criticality:'tier_1'|'tier_2'|'tier_3'; title:string; owner_id:string|null; rto_minutes:number; rpo_minutes:number; status:'draft'|'active'|'needs_review'|'retired'; last_reviewed_at:string|null; next_review_at:string|null; latest_checkpoint_at:string|null; latest_drill_status:string|null };
export type ContinuitySnapshot = { generated_at:string; metrics:{plans:number;tier_1:number;active:number;needs_review:number;drills_due:number;failed_drills:number;checkpoint_evidence_90d:number}; plans:ContinuityPlan[] };

export async function getBusinessContinuity360(){ const {data,error}=await supabase.rpc('get_business_continuity_360'); if(error) throw error; return data as ContinuitySnapshot; }
export async function createBusinessContinuityPlan(input:{domain:string;criticality:string;title:string;ownerId?:string;rtoMinutes:number;rpoMinutes:number;recoveryProcedure:string;nextReviewAt?:string}){ const {data,error}=await supabase.rpc('create_business_continuity_plan',{p_domain:input.domain,p_criticality:input.criticality,p_title:input.title,p_owner_id:input.ownerId??null,p_rto_minutes:input.rtoMinutes,p_rpo_minutes:input.rpoMinutes,p_recovery_procedure:input.recoveryProcedure,p_next_review_at:input.nextReviewAt??null}); if(error) throw error; return data; }
export async function recordRecoveryDrill(input:{planId:string;drillType:string;scheduledAt:string;status?:string;outcome?:string;evidenceReference?:string;issuesFound?:number}){ const {data,error}=await supabase.rpc('record_recovery_drill',{p_plan_id:input.planId,p_drill_type:input.drillType,p_scheduled_at:input.scheduledAt,p_status:input.status??'planned',p_outcome:input.outcome??null,p_evidence_reference:input.evidenceReference??null,p_issues_found:input.issuesFound??0}); if(error) throw error; return data; }
export async function recordRecoveryCheckpoint(input:{planId:string;checkpointType:string;evidenceReference?:string;notes?:string}){ const {data,error}=await supabase.rpc('record_recovery_checkpoint',{p_plan_id:input.planId,p_checkpoint_type:input.checkpointType,p_evidence_reference:input.evidenceReference??null,p_notes:input.notes??null}); if(error) throw error; return data; }
