import type { CMSContentStore } from './cms-types';
import {
  MOCK_HERO_SLIDES,
  MOCK_SERVICES,
  MOCK_TESTIMONIALS,
  MOCK_PARTNERS,
  MOCK_PROJECTS,
} from './mock-data';

const DEFAULT_FAQS = [
  {
    id: "1",
    question: "What types of flooring do you offer?",
    answer: "We specialize in industrial flooring, epoxy coatings, concrete sealers, polished concrete, and decorative flooring solutions for commercial and residential spaces.",
    category: "Flooring",
    display_order: 1,
  },
  {
    id: "2",
    question: "Do you provide waterproofing services?",
    answer: "Yes, we offer comprehensive waterproofing including APP bituminous membrane, basement waterproofing, roof coating, foundation waterproofing, and wet area waterproofing.",
    category: "Waterproofing",
    display_order: 2,
  },
  {
    id: "3",
    question: "How long does a typical flooring project take?",
    answer: "Project duration depends on scope and size. A standard industrial floor can take 3-7 days including preparation, application, and curing. We provide a detailed timeline during consultation.",
    category: "Flooring",
    display_order: 3,
  },
  {
    id: "4",
    question: "Do you offer free quotations?",
    answer: "Yes, we provide free, no-obligation quotations for all projects. Fill out our quotation form or contact us directly and we'll get back to you within 24 hours.",
    category: "General",
    display_order: 4,
  },
  {
    id: "5",
    question: "What areas do you serve?",
    answer: "We serve commercial, industrial, and residential clients across all regional metro zones. Contact us to confirm service availability for your specific location.",
    category: "General",
    display_order: 5,
  },
  {
    id: "6",
    question: "Are your materials and services guaranteed?",
    answer: "Yes, we use high-quality materials from certified global brands and provide workmanship guarantees on all our installations. Specific warranty periods depend on the project type.",
    category: "General",
    display_order: 6,
  },
  {
    id: "7",
    question: "How do I maintain my epoxy floor?",
    answer: "Epoxy floors are low maintenance. Regular sweeping and occasional damp mopping with mild detergent is sufficient. Avoid harsh chemicals and use protective pads under heavy equipment.",
    category: "Flooring",
    display_order: 7,
  },
];

export const DEFAULT_CMS_STORE: CMSContentStore = {
  website_settings: {
    site_info: {
      name: 'Your Flooring Company',
      tagline: 'Professional Flooring & Waterproofing Solutions',
      logo_url: '',
      favicon_url: '/favicon.svg',
      description: 'Premier provider of commercial, industrial, and residential flooring systems.',
      url: 'https://example.com',
    },
    company: {
      name: 'Your Flooring Company',
      legal_name: 'Your Flooring Company LLC',
      tax_id: 'XX-XXXXXXX',
      registration_number: 'REG-000000',
    },
    contact: {
      email: 'contact@example.com',
      phone: '+1 (555) 000-0000',
      whatsapp: '+15550000000',
      address: '123 Commerce Way, Suite 100',
      city: 'Metropolis',
      working_hours: 'Mon - Fri: 8:00 AM - 6:00 PM, Sat: 9:00 AM - 2:00 PM',
    },
    social: {
      facebook: 'https://facebook.com',
      instagram: 'https://instagram.com',
      linkedin: 'https://linkedin.com',
      twitter: 'https://twitter.com',
      youtube: 'https://youtube.com',
    },
    localization: {
      currency_code: 'USD',
      currency_symbol: '$',
      language: 'en-US',
      timezone: 'America/New_York',
    },
  },

  homepage: {
    hero_slides: MOCK_HERO_SLIDES,
    value_props: [
      {
        id: '1',
        title: 'Certified Technicians',
        subtitle: 'Fully trained & accredited installation crews',
        icon: 'Award',
        description: 'Our installation teams bring years of specialized surface preparation expertise.',
      },
      {
        id: '2',
        title: 'Premium Grade Materials',
        subtitle: 'Industrial quality resin, epoxy & timber',
        icon: 'ShieldCheck',
        description: 'We source high-durability coatings engineered for seamless long-term protection.',
      },
      {
        id: '3',
        title: 'Warranty Guaranteed',
        subtitle: 'Comprehensive structural coverage',
        icon: 'CheckCircle2',
        description: 'Backed by robust manufacturer warranties and rigorous post-installation checks.',
      },
      {
        id: '4',
        title: 'Rapid Turnaround',
        subtitle: 'Minimal downtime for ongoing operations',
        icon: 'Clock',
        description: 'Fast-curing resin technology allows high-traffic environments to resume rapidly.',
      },
    ],
    sections: [
      {
        id: 'sec-1',
        section_type: 'hero',
        section_key: 'main_hero',
        title: 'Transform Your Spaces With Flooring Excellence',
        subtitle: 'Durability, Precision, and Superior Aesthetic Finish',
        content: { cta_primary: 'Get Free Quote', cta_secondary: 'Explore Services' },
        display_order: 1,
        is_active: true,
        background_color: null,
        background_image: null,
        padding: 'py-12',
      },
      {
        id: 'sec-2',
        section_type: 'featured_services',
        section_key: 'services_overview',
        title: 'Our Core Flooring Services',
        subtitle: 'Tailored Solutions for Industrial, Commercial, and Residential Spaces',
        content: { limit: 6 },
        display_order: 2,
        is_active: true,
        background_color: '#f8fafc',
        background_image: null,
        padding: 'py-16',
      },
    ],
    banner: {
      title: 'Ready to Upgrade Your Surfaces?',
      subtitle: 'Schedule a free site survey and personalized estimate today.',
      button_text: 'Request Free Quote',
      button_link: '/quotation',
      background_image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1600&q=80',
      is_active: true,
    },
  },

  about: {
    hero: {
      title: 'About Our Company',
      subtitle: 'Delivering High-Performance Surface Solutions Since 2012',
      background_image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80',
    },
    story: {
      heading: 'Engineered Surface Perfection',
      paragraph_1: 'Founded on the principles of mechanical precision and material science, our company provides end-to-end flooring and waterproofing systems. From heavy manufacturing plants to luxury architectural developments, we tailor each installation to client demand.',
      paragraph_2: 'We utilize advanced surface grinding, vacuum shot-blasting, and moisture mitigation treatments to ensure lifetime adhesion and flawless aesthetic visual appeal.',
      image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    },
    mission: {
      title: 'Our Mission',
      description: 'To provide durable, sustainable, and aesthetically superior surface finishes that exceed industrial standards and enhance space usability.',
    },
    vision: {
      title: 'Our Vision',
      description: 'To be the benchmark for architectural and industrial coating solutions across residential, commercial, and heavy manufacturing sectors.',
    },
    core_values: [
      { title: 'Quality First', description: 'Zero compromise on substrate prep, primer quality, and topcoat wear resistance.', icon: 'Shield' },
      { title: 'Integrity & Safety', description: 'Transparent scope pricing, adherence to VOC compliance, and certified site protocols.', icon: 'CheckSquare' },
      { title: 'Technical Expertise', description: 'Continuous staff certification in resin formulations and acoustic wood sub-flooring.', icon: 'Layers' },
    ],
    stats: [
      { label: 'Completed Projects', value: '500', suffix: '+' },
      { label: 'Square Feet Installed', value: '2.5M', suffix: '+' },
      { label: 'Client Satisfaction', value: '99.4', suffix: '%' },
      { label: 'Years Experience', value: '12', suffix: '+' },
    ],
    team: [
      {
        name: 'Technical Director',
        role: 'Chief Surface Engineer',
        bio: '15+ years overseeing heavy industrial polymer and terrazzo installations.',
        avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
      },
      {
        name: 'Operations Manager',
        role: 'Head of Site Operations',
        bio: 'Specialist in project scheduling, quality control audits, and team safety compliance.',
        avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
      },
    ],
  },

  services: {
    catalog: MOCK_SERVICES.map((s) => ({
      id: s.id,
      title: s.title,
      slug: s.slug,
      description: s.description,
      short_description: s.short_description,
      icon: s.icon,
      image_url: s.image_url,
      features: s.features,
      is_active: s.is_active,
      display_order: s.display_order,
    })),
    categories: ['All', 'Resin & Epoxy', 'Waterproofing', 'Timber & Wood', 'Concrete', 'Sports Flooring'],
    process_steps: [
      {
        step_number: 1,
        title: 'Initial Consultation & Site Audit',
        description: 'We inspect substrate condition, measure moisture levels, and assess load requirements.',
        icon: 'Search',
      },
      {
        step_number: 2,
        title: 'Substrate Preparation',
        description: 'Mechanical diamond grinding and shot-blasting to achieve required concrete surface profiles.',
        icon: 'Tool',
      },
      {
        step_number: 3,
        title: 'System Application',
        description: 'Precision application of moisture barriers, screeds, body coats, and topcoats.',
        icon: 'Layers',
      },
      {
        step_number: 4,
        title: 'Quality Inspection & Handover',
        description: 'Strict adhesion tests, gloss checks, site cleanup, and warranty certificate issuance.',
        icon: 'CheckCircle',
      },
    ],
    cta_banner: {
      title: 'Need Custom Technical Specifications?',
      subtitle: 'Our technical team is ready to draft a customized specification sheet for your architect or engineer.',
      button_text: 'Talk To An Specialist',
      link: '/contact',
    },
  },

  projects: {
    portfolio: MOCK_PROJECTS,
    map_locations: [
      { id: '1', title: 'Central Metro Commercial Plaza', lat: 38.8951, lng: -77.0364, region: 'Central District', location_text: 'Central Metro' },
      { id: '2', title: 'Industrial Logistics Hub', lat: 38.8800, lng: -77.0400, region: 'Industrial Zone', location_text: 'Industrial Zone' },
      { id: '3', title: 'Westside Residential Complex', lat: 38.9000, lng: -77.0500, region: 'West District', location_text: 'West District' },
    ],
    material_specs: [
      'Self-Leveling Epoxy Resin',
      'Polyurethane Cement Screed',
      'Engineered Hardwood Timber',
      'Heavy Duty Terrazzo Aggregate',
      'Flexible Waterproofing Membrane',
    ],
  },

  gallery: {
    items: MOCK_PROJECTS.map((p) => ({
      id: p.id,
      title: p.title,
      category: p.category || 'Epoxy',
      before_image_url: p.images?.find((img) => img.image_type === 'before')?.image_url || 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=800&q=80',
      after_image_url: p.images?.find((img) => img.image_type === 'after')?.image_url || p.images?.[0]?.image_url || 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
      description: p.description || 'Flooring transformation showcase project.',
      tags: [p.category || 'Epoxy', p.service_type || 'Commercial'],
    })),
    categories: ['All', 'Epoxy Flooring', 'Waterproofing', 'Wood & Hardwood', 'Commercial'],
  },

  testimonials: {
    reviews: MOCK_TESTIMONIALS,
    corporate_partners: MOCK_PARTNERS,
    trust_metrics: {
      rating: 4.9,
      total_reviews: 128,
      satisfaction_rate: '99.4%',
    },
  },

  faq: {
    items: DEFAULT_FAQS,
    categories: ['All', 'General', 'Epoxy Flooring', 'Waterproofing', 'Hardwood', 'Maintenance', 'Pricing'],
  },

  contact: {
    header: {
      title: 'Get In Touch',
      subtitle: 'Have a project in mind? Speak with our surface specialists today.',
    },
    offices: [
      {
        name: 'Headquarters & Showroom',
        address: '123 Commerce Way, Suite 100, Metropolis',
        phone: '+1 (555) 000-0000',
        email: 'contact@example.com',
        working_hours: 'Mon - Fri: 8:00 AM - 6:00 PM',
        lat: 38.8951,
        lng: -77.0364,
        is_primary: true,
      },
    ],
    map_settings: {
      center_lat: 38.8951,
      center_lng: -77.0364,
      zoom: 12,
    },
    form_options: {
      project_types: ['Industrial Epoxy', 'Commercial Flooring', 'Residential Wood', 'Waterproofing', 'Subfloor Repair', 'Other'],
      budget_ranges: ['$1,000 - $5,000', '$5,000 - $15,000', '$15,000 - $50,000', '$50,000+'],
      enable_attachment: true,
    },
  },

  footer: {
    columns: [
      {
        title: 'Services',
        links: [
          { label: 'Epoxy Flooring', href: '/services/epoxy-flooring' },
          { label: 'Waterproofing', href: '/services/waterproofing-solutions' },
          { label: 'Hardwood Timber', href: '/services/hardwood-timber-flooring' },
          { label: 'Polished Concrete', href: '/services/polished-concrete' },
        ],
      },
      {
        title: 'Quick Links',
        links: [
          { label: 'About Us', href: '/about' },
          { label: 'Projects Portfolio', href: '/portfolio' },
          { label: 'Request Quotation', href: '/quotation' },
          { label: 'FAQ', href: '/faq' },
          { label: 'Contact Us', href: '/contact' },
        ],
      },
      {
        title: 'Customer Support',
        links: [
          { label: 'Track Order', href: '/track-order' },
          { label: 'Admin Panel', href: '/admin/login' },
          { label: 'Terms & Conditions', href: '/faq' },
          { label: 'Privacy Policy', href: '/faq' },
        ],
      },
    ],
    copyright: '© 2026 Your Flooring Company. All rights reserved.',
    legal_disclaimer: 'Content and project imagery can be edited directly via the CMS Admin Panel.',
    newsletter: {
      title: 'Stay Informed',
      description: 'Subscribe to receive news on surface trends, care guides, and promotional discounts.',
      placeholder: 'Enter your email address',
      button_text: 'Subscribe',
    },
  },

  seo: {
    pages: {
      home: {
        id: 'seo-home',
        page_type: 'home',
        page_id: null,
        meta_title: 'Your Flooring Company | Professional Flooring & Waterproofing Solutions',
        meta_description: 'Premier provider of high-performance epoxy, hardwood, waterproofing, and industrial flooring solutions.',
        meta_keywords: 'flooring, epoxy, waterproofing, hardwood, polished concrete',
        og_title: 'Your Flooring Company | Surface Solutions',
        og_description: 'High-performance residential, commercial, and industrial surface solutions.',
        og_image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80',
        canonical_url: 'https://example.com/',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      about: {
        id: 'seo-about',
        page_type: 'about',
        page_id: null,
        meta_title: 'About Us | Your Flooring Company',
        meta_description: 'Learn about our dedication to surface engineering, quality materials, and certified installation.',
        meta_keywords: 'about flooring company, floor contractors, certified installers',
        og_title: 'About Your Flooring Company',
        og_description: 'Discover our mission, team, and high-performance surface solutions.',
        og_image: null,
        canonical_url: 'https://example.com/about',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      services: {
        id: 'seo-services',
        page_type: 'services',
        page_id: null,
        meta_title: 'Flooring Services & Solutions | Your Flooring Company',
        meta_description: 'Explore our full range of epoxy, waterproofing, hardwood, terrazzo, and concrete coating services.',
        meta_keywords: 'flooring services, epoxy installation, waterproofing contractors',
        og_title: 'Flooring & Waterproofing Services',
        og_description: 'Comprehensive surface solutions for commercial, industrial, and residential projects.',
        og_image: null,
        canonical_url: 'https://example.com/services',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      portfolio: {
        id: 'seo-portfolio',
        page_type: 'portfolio',
        page_id: null,
        meta_title: 'Project Portfolio & Case Studies | Your Flooring Company',
        meta_description: 'Browse completed commercial, industrial, and residential flooring projects.',
        meta_keywords: 'flooring portfolio, case studies, epoxy before after',
        og_title: 'Flooring Projects Showcase',
        og_description: 'View real project transformations and material specifications.',
        og_image: null,
        canonical_url: 'https://example.com/portfolio',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      faq: {
        id: 'seo-faq',
        page_type: 'faq',
        page_id: null,
        meta_title: 'Frequently Asked Questions | Your Flooring Company',
        meta_description: 'Answers to common questions about epoxy curing, substrate prep, waterproofing, and pricing.',
        meta_keywords: 'flooring faq, epoxy drying time, floor maintenance tips',
        og_title: 'Flooring FAQs & Knowledge Base',
        og_description: 'Get clear answers regarding flooring specs, warranties, and care.',
        og_image: null,
        canonical_url: 'https://example.com/faq',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      contact: {
        id: 'seo-contact',
        page_type: 'contact',
        page_id: null,
        meta_title: 'Contact Us | Your Flooring Company',
        meta_description: 'Reach out to our specialists or schedule a free site survey and estimate.',
        meta_keywords: 'contact flooring contractors, free estimate, flooring quote',
        og_title: 'Contact Your Flooring Company',
        og_description: 'Connect with our team for site inspections and custom proposals.',
        og_image: null,
        canonical_url: 'https://example.com/contact',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
    },
    global_default: {
      site_name: 'Your Flooring Company',
      title_template: '%s | Your Flooring Company',
      default_description: 'Professional flooring and waterproofing solutions.',
      default_og_image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80',
      default_keywords: 'flooring, epoxy, waterproofing, hardwood',
    },
  },

  media_library: {
    folders: [
      { id: 'fold-1', name: 'Hero Banners', parent_id: null, display_order: 1 },
      { id: 'fold-2', name: 'Service Highlights', parent_id: null, display_order: 2 },
      { id: 'fold-3', name: 'Projects Portfolio', parent_id: null, display_order: 3 },
    ],
    files: [],
  },

  theme_settings: {
    preset: 'gold-amber',
    primary_color: '#b45309',
    secondary_color: '#1e293b',
    accent_color: '#d97706',
    heading_font: 'Plus Jakarta Sans',
    body_font: 'Inter',
    button_style: 'rounded-md',
    border_radius: 6,
    spacing_scale: 1,
    layout_style: 'classic',
  },
};
