import type { CMSContentStore } from './cms-types';

const DEFAULT_FAQS = [
  {
    id: "1",
    question: "What types of flooring do you offer?",
    answer: "We specialize in industrial flooring, epoxy coatings, concrete sealers, polished concrete, and decorative flooring solutions for commercial and residential spaces.",
    category: "Flooring",
    display_order: 1,
  },
  {
    id: "2",
    question: "Do you provide waterproofing services?",
    answer: "Yes, we offer comprehensive waterproofing including APP bituminous membrane, basement waterproofing, roof coating, foundation waterproofing, and wet area waterproofing.",
    category: "Waterproofing",
    display_order: 2,
  },
  {
    id: "3",
    question: "How long does a typical flooring project take?",
    answer: "Project duration depends on scope and size. A standard industrial floor can take 3-7 days including preparation, application, and curing. We provide a detailed timeline during consultation.",
    category: "Flooring",
    display_order: 3,
  },
  {
    id: "4",
    question: "Do you offer free quotations?",
    answer: "Yes, we provide free, no-obligation quotations for all projects. Fill out our quotation form or contact us directly and we'll get back to you within 24 hours.",
    category: "General",
    display_order: 4,
  },
  {
    id: "5",
    question: "What areas do you serve?",
    answer: "We serve commercial, industrial, and residential clients across all regional metro zones. Contact us to confirm service availability for your specific location.",
    category: "General",
    display_order: 5,
  },
  {
    id: "6",
    question: "Are your materials and services guaranteed?",
    answer: "Yes, we use high-quality materials from certified global brands and provide workmanship guarantees on all our installations. Specific warranty periods depend on the project type.",
    category: "General",
    display_order: 6,
  },
  {
    id: "7",
    question: "How do I maintain my epoxy floor?",
    answer: "Epoxy floors are low maintenance. Regular sweeping and occasional damp mopping with mild detergent is sufficient. Avoid harsh chemicals and use protective pads under heavy equipment.",
    category: "Flooring",
    display_order: 7,
  },
];

export const DEFAULT_CMS_STORE: CMSContentStore = {
  website_settings: {
    site_info: {
      name: 'Topline Flooring and Waterproofing',
      tagline: 'Professional Flooring & Waterproofing Solutions',
      logo_url: '',
      favicon_url: '/favicon.svg',
      description: 'Premier provider of commercial, industrial, and residential flooring systems.',
      url: 'https://toplineflooringandwaterproofing.co.ke',
    },
    company: {
      name: 'Topline Flooring and Waterproofing',
      legal_name: 'Topline Flooring and Waterproofing',
      tax_id: '',
      registration_number: '',
    },
    contact: {
      email: 'toplineflooringandwaterproofin@gmail.com',
      phone: '0720 859 737 / 0755 293 372',
      whatsapp: '+254720859737',
      address: 'Nairobi, Kenya',
      city: 'Nairobi',
      working_hours: 'Contact us for current business hours',
    },
    social: {
      facebook: '',
      instagram: '',
      linkedin: '',
      twitter: '',
      youtube: '',
    },
    localization: {
      currency_code: 'KES',
      currency_symbol: 'KSh',
      language: 'en-KE',
      timezone: 'Africa/Nairobi',
    },
  },

  homepage: {
    hero_slides: [],
    value_props: [
      {
        id: '1',
        title: 'Certified Technicians',
        subtitle: 'Fully trained & accredited installation crews',
        icon: 'Award',
        description: 'Our installation teams bring years of specialized surface preparation expertise.',
      },
      {
        id: '2',
        title: 'Premium Grade Materials',
        subtitle: 'Industrial quality resin, epoxy & timber',
        icon: 'ShieldCheck',
        description: 'We source high-durability coatings engineered for seamless long-term protection.',
      },
      {
        id: '3',
        title: 'Warranty Guaranteed',
        subtitle: 'Comprehensive structural coverage',
        icon: 'CheckCircle2',
        description: 'Backed by robust manufacturer warranties and rigorous post-installation checks.',
      },
      {
        id: '4',
        title: 'Rapid Turnaround',
        subtitle: 'Minimal downtime for ongoing operations',
        icon: 'Clock',
        description: 'Fast-curing resin technology allows high-traffic environments to resume rapidly.',
      },
    ],
    sections: [
      {
        id: 'sec-1',
        section_type: 'hero',
        section_key: 'main_hero',
        title: 'Transform Your Spaces With Flooring Excellence',
        subtitle: 'Durability, Precision, and Superior Aesthetic Finish',
        content: { cta_primary: 'Get Free Quote', cta_secondary: 'Explore Services' },
        display_order: 1,
        is_active: true,
        background_color: null,
        background_image: null,
        padding: 'py-12',
      },
      {
        id: 'sec-2',
        section_type: 'featured_services',
        section_key: 'services_overview',
        title: 'Our Core Flooring Services',
        subtitle: 'Tailored Solutions for Industrial, Commercial, and Residential Spaces',
        content: { limit: 6 },
        display_order: 2,
        is_active: true,
        background_color: '#f8fafc',
        background_image: null,
        padding: 'py-16',
      },
    ],
    banner: {
      title: 'Ready to Upgrade Your Surfaces?',
      subtitle: 'Schedule a free site survey and personalized estimate today.',
      button_text: 'Request Free Quote',
      button_link: '/quotation',
      background_image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1600&q=80',
      is_active: true,
    },
  },

  about: {
    hero: {
      title: 'About Our Company',
      subtitle: 'Flooring and waterproofing solutions for residential, commercial and industrial spaces',
      background_image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1600&q=80',
    },
    story: {
      heading: 'Engineered Surface Perfection',
      paragraph_1: 'Topline Flooring and Waterproofing provides flooring, waterproofing, concrete protection and related surface solutions for residential, commercial and industrial clients in Kenya.',
      paragraph_2: 'Project scope, preparation requirements, materials and installation methods are assessed for each site so that the recommended system matches the client's building and operational needs.',
      image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=800&q=80',
    },
    mission: {
      title: 'Our Mission',
      description: 'To provide durable, sustainable, and aesthetically superior surface finishes that exceed industrial standards and enhance space usability.',
    },
    vision: {
      title: 'Our Vision',
      description: 'To be the benchmark for architectural and industrial coating solutions across residential, commercial, and heavy manufacturing sectors.',
    },
    core_values: [
      { title: 'Quality First', description: 'Zero compromise on substrate prep, primer quality, and topcoat wear resistance.', icon: 'Shield' },
      { title: 'Integrity & Safety', description: 'Transparent scope pricing, adherence to VOC compliance, and certified site protocols.', icon: 'CheckSquare' },
      { title: 'Technical Expertise', description: 'Continuous staff certification in resin formulations and acoustic wood sub-flooring.', icon: 'Layers' },
    ],
    stats: [],
    team: [],
  },

  services: {
    catalog: [],
    categories: ['All', 'Resin & Epoxy', 'Waterproofing', 'Timber & Wood', 'Concrete', 'Sports Flooring'],
    process_steps: [
      {
        step_number: 1,
        title: 'Initial Consultation & Site Audit',
        description: 'We inspect substrate condition, measure moisture levels, and assess load requirements.',
        icon: 'Search',
      },
      {
        step_number: 2,
        title: 'Substrate Preparation',
        description: 'Mechanical diamond grinding and shot-blasting to achieve required concrete surface profiles.',
        icon: 'Tool',
      },
      {
        step_number: 3,
        title: 'System Application',
        description: 'Precision application of moisture barriers, screeds, body coats, and topcoats.',
        icon: 'Layers',
      },
      {
        step_number: 4,
        title: 'Quality Inspection & Handover',
        description: 'Strict adhesion tests, gloss checks, site cleanup, and warranty certificate issuance.',
        icon: 'CheckCircle',
      },
    ],
    cta_banner: {
      title: 'Need Custom Technical Specifications?',
      subtitle: 'Our technical team is ready to draft a customized specification sheet for your architect or engineer.',
      button_text: 'Talk To An Specialist',
      link: '/contact',
    },
  },

  projects: {
    portfolio: [],
    map_locations: [],
    material_specs: [
      'Self-Leveling Epoxy Resin',
      'Polyurethane Cement Screed',
      'Engineered Hardwood Timber',
      'Heavy Duty Terrazzo Aggregate',
      'Flexible Waterproofing Membrane',
    ],
  },

  gallery: {
    items: [],
    categories: ['All', 'Epoxy Flooring', 'Waterproofing', 'Wood & Hardwood', 'Commercial'],
  },

  testimonials: {
    reviews: [],
    corporate_partners: [],
    trust_metrics: {
      rating: 0,
      total_reviews: 0,
      satisfaction_rate: '',
    },
  },

  faq: {
    items: DEFAULT_FAQS,
    categories: ['All', 'General', 'Epoxy Flooring', 'Waterproofing', 'Hardwood', 'Maintenance', 'Pricing'],
  },

  contact: {
    header: {
      title: 'Get In Touch',
      subtitle: 'Have a project in mind? Speak with our surface specialists today.',
    },
    offices: [
      {
        name: 'Headquarters & Showroom',
        address: 'Nairobi, Kenya',
        phone: '0720 859 737 / 0755 293 372',
        email: 'toplineflooringandwaterproofin@gmail.com',
        working_hours: 'Mon - Fri: 8:00 AM - 6:00 PM',
        lat: 1.286389,
        lng: 36.817223,
        is_primary: true,
      },
    ],
    map_settings: {
      center_lat: 1.286389,
      center_lng: 36.817223,
      zoom: 12,
    },
    form_options: {
      project_types: ['Industrial Epoxy', 'Commercial Flooring', 'Residential Wood', 'Waterproofing', 'Subfloor Repair', 'Other'],
      budget_ranges: ['Below KSh 100,000', 'KSh 100,000 - 500,000', 'KSh 500,000 - 1,000,000', 'Above KSh 1,000,000'],
      enable_attachment: true,
    },
  },

  footer: {
    columns: [
      {
        title: 'Services',
        links: [
          { label: 'Epoxy Flooring', href: '/services/epoxy-flooring' },
          { label: 'Waterproofing', href: '/services/waterproofing-solutions' },
          { label: 'Hardwood Timber', href: '/services/hardwood-timber-flooring' },
          { label: 'Polished Concrete', href: '/services/polished-concrete' },
        ],
      },
      {
        title: 'Quick Links',
        links: [
          { label: 'About Us', href: '/about' },
          { label: 'Projects Portfolio', href: '/portfolio' },
          { label: 'Request Quotation', href: '/quotation' },
          { label: 'FAQ', href: '/faq' },
          { label: 'Contact Us', href: '/contact' },
        ],
      },
      {
        title: 'Customer Support',
        links: [
          { label: 'Track Order', href: '/track-order' },
          { label: 'Admin Panel', href: '/admin/login' },
          { label: 'Terms & Conditions', href: '/faq' },
          { label: 'Privacy Policy', href: '/faq' },
        ],
      },
    ],
    copyright: '© 2026 Topline Flooring and Waterproofing. All rights reserved.',
    legal_disclaimer: 'Content and project imagery can be edited directly via the CMS Admin Panel.',
    newsletter: {
      title: 'Stay Informed',
      description: 'Subscribe to receive news on surface trends, care guides, and promotional discounts.',
      placeholder: 'Enter your email address',
      button_text: 'Subscribe',
    },
  },

  seo: {
    pages: {
      home: {
        id: 'seo-home',
        page_type: 'home',
        page_id: null,
        meta_title: 'Topline Flooring and Waterproofing | Flooring & Waterproofing Solutions',
        meta_description: 'Premier provider of high-performance epoxy, hardwood, waterproofing, and industrial flooring solutions.',
        meta_keywords: 'flooring, epoxy, waterproofing, hardwood, polished concrete',
        og_title: 'Topline Flooring and Waterproofing | Surface Solutions',
        og_description: 'High-performance residential, commercial, and industrial surface solutions.',
        og_image: 'https://images.unsplash.com/photo-1581858726788-75bc0f6a952d?auto=format&fit=crop&w=1200&q=80',
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      about: {
        id: 'seo-about',
        page_type: 'about',
        page_id: null,
        meta_title: 'About Topline Flooring and Waterproofing',
        meta_description: 'Learn about our dedication to surface engineering, quality materials, and certified installation.',
        meta_keywords: 'about flooring company, floor contractors, certified installers',
        og_title: 'About Topline Flooring and Waterproofing',
        og_description: 'Discover our mission, team, and high-performance surface solutions.',
        og_image: null,
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/about',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      services: {
        id: 'seo-services',
        page_type: 'services',
        page_id: null,
        meta_title: 'Flooring & Waterproofing Services | Topline',
        meta_description: 'Explore our full range of epoxy, waterproofing, hardwood, terrazzo, and concrete coating services.',
        meta_keywords: 'flooring services, epoxy installation, waterproofing contractors',
        og_title: 'Flooring & Waterproofing Services',
        og_description: 'Comprehensive surface solutions for commercial, industrial, and residential projects.',
        og_image: null,
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/services',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      portfolio: {
        id: 'seo-portfolio',
        page_type: 'portfolio',
        page_id: null,
        meta_title: 'Projects & Case Studies | Topline Flooring and Waterproofing',
        meta_description: 'Browse completed commercial, industrial, and residential flooring projects.',
        meta_keywords: 'flooring portfolio, case studies, epoxy before after',
        og_title: 'Flooring Projects Showcase',
        og_description: 'View real project transformations and material specifications.',
        og_image: null,
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/portfolio',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      faq: {
        id: 'seo-faq',
        page_type: 'faq',
        page_id: null,
        meta_title: 'FAQs | Topline Flooring and Waterproofing',
        meta_description: 'Answers to common questions about epoxy curing, substrate prep, waterproofing, and pricing.',
        meta_keywords: 'flooring faq, epoxy drying time, floor maintenance tips',
        og_title: 'Flooring FAQs & Knowledge Base',
        og_description: 'Get clear answers regarding flooring specs, warranties, and care.',
        og_image: null,
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/faq',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
      contact: {
        id: 'seo-contact',
        page_type: 'contact',
        page_id: null,
        meta_title: 'Contact Topline Flooring and Waterproofing',
        meta_description: 'Reach out to our specialists or schedule a free site survey and estimate.',
        meta_keywords: 'contact flooring contractors, free estimate, flooring quote',
        og_title: 'Contact Topline Flooring and Waterproofing',
        og_description: 'Connect with our team for site inspections and custom proposals.',
        og_image: null,
        canonical_url: 'https://toplineflooringandwaterproofing.co.ke/contact',
        structured_data: null,
        no_index: false,
        no_follow: false,
      },
    },
    global_default: {
      site_name: 'Topline Flooring and Waterproofing',
      title_template: '%s | Topline Flooring and Waterproofing',
      default_description: 'Professional flooring and waterproofing solutions.',
      default_og_image: null,
      default_keywords: 'flooring, epoxy, waterproofing, hardwood',
    },
  },

  media_library: {
    folders: [
      { id: 'fold-1', name: 'Hero Banners', parent_id: null, display_order: 1 },
      { id: 'fold-2', name: 'Service Highlights', parent_id: null, display_order: 2 },
      { id: 'fold-3', name: 'Projects Portfolio', parent_id: null, display_order: 3 },
    ],
    files: [],
  },

  theme_settings: {
    preset: 'gold-amber',
    primary_color: '#b45309',
    secondary_color: '#1e293b',
    accent_color: '#d97706',
    heading_font: 'Plus Jakarta Sans',
    body_font: 'Inter',
    button_style: 'rounded-md',
    border_radius: 6,
    spacing_scale: 1,
    layout_style: 'classic',
  },
};
