import type {
  Product,
  Category,
  HeroSlide,
  Service,
  Testimonial,
  Partner,
  Project,
  DeliveryZone,
} from './types';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Epoxy Flooring Systems',
    slug: 'epoxy-flooring',
    description: 'Heavy-duty seamless epoxy coatings designed for high-traffic industrial and commercial environments.',
    image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=800&q=80',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Polyurethane Flooring',
    slug: 'polyurethane-flooring',
    description: 'Thermal-shock resistant polyurethane screeds ideal for food processing plants and cold rooms.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-3',
    name: 'Waterproofing Systems',
    slug: 'waterproofing-systems',
    description: 'Liquid elastomeric membranes and crystalline waterproofing for roofs, basements, and wet areas.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Joint Sealants & Adhesives',
    slug: 'joint-sealants',
    description: 'Flexible polyurethane and silicone sealants for expansion joints and structural seals.',
    image_url: 'https://images.unsplash.com/photo-1615840728552-7073c8c5d6c5?auto=format&fit=crop&w=800&q=80',
    display_order: 4,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'cat-5',
    name: 'Concrete Hardener & Sealers',
    slug: 'concrete-sealers',
    description: 'Lithium silicate hardeners that densify concrete surfaces to eliminate dust and resist wear.',
    image_url: 'https://images.unsplash.com/photo-1503387762-592deb587942?auto=format&fit=crop&w=800&q=80',
    display_order: 5,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    category_id: 'cat-1',
    name: 'Pro Heavy-Duty Industrial Epoxy Coating (15kg Kit)',
    slug: 'pro-heavy-duty-industrial-epoxy-coating',
    description: 'High-build, 100% solids epoxy resin system providing a seamless, chemical-resistant finish for warehouse floors, manufacturing plants, and auto workshops.',
    short_description: '100% solids heavy-duty epoxy coating for industrial floors.',
    price: 14500,
    unit: 'Kit',
    image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    ],
    featured: true,
    in_stock: true,
    display_order: 1,
    is_active: true,
    brand_id: null,
    sku: 'PRO-EPX-15K',
    meta_title: 'Pro Heavy-Duty Industrial Epoxy Coating',
    meta_description: 'Buy 100% solids industrial epoxy floor coating for heavy-duty facilities.',
    stock_quantity: 45,
    low_stock_threshold: 10,
    related_products: ['prod-2', 'prod-4'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
    specifications: [
      { id: 's1', product_id: 'prod-1', spec_name: 'Coverage', spec_value: '25-30 sq meters per kit', display_order: 1 },
      { id: 's2', product_id: 'prod-1', spec_name: 'Cure Time', spec_value: '24 hours foot traffic, 7 days full cure', display_order: 2 },
      { id: 's3', product_id: 'prod-1', spec_name: 'Compressive Strength', spec_value: '> 70 MPa', display_order: 3 },
    ],
  },
  {
    id: 'prod-2',
    category_id: 'cat-2',
    name: 'Pro PU Mortar Heavy-Duty Screed (25kg)',
    slug: 'pro-pu-mortar-screed',
    description: 'Heavy-duty polyurethane resin screed system designed for steam cleaning, extreme thermal shocks (-40°C to 120°C), and food industry hygiene.',
    short_description: 'Thermal-shock resistant polyurethane screed for food & pharma plants.',
    price: 18500,
    unit: 'Bag',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
    ],
    featured: true,
    in_stock: true,
    display_order: 2,
    is_active: true,
    brand_id: null,
    sku: 'PRO-PU-25K',
    meta_title: 'Pro PU Mortar Heavy-Duty Screed',
    meta_description: 'Polyurethane flooring screed for cold rooms and processing plants.',
    stock_quantity: 30,
    low_stock_threshold: 5,
    related_products: ['prod-1'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'prod-3',
    category_id: 'cat-3',
    name: 'Pro Elastomeric Liquid Waterproofing Membrane (20L)',
    slug: 'elastomeric-liquid-waterproofing-membrane',
    description: 'UV-resistant, seamless polyurethane liquid membrane for waterproofing flat roofs, balconies, podium decks, and wet rooms.',
    short_description: 'Seamless elastomeric liquid membrane for roofs and balconies.',
    price: 13800,
    unit: 'Bucket',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    ],
    featured: true,
    in_stock: true,
    display_order: 3,
    is_active: true,
    brand_id: null,
    sku: 'PRO-WPF-20L',
    meta_title: 'Pro Elastomeric Liquid Waterproofing Membrane',
    meta_description: 'Liquid waterproofing membrane for roof decks and foundations.',
    stock_quantity: 60,
    low_stock_threshold: 15,
    related_products: ['prod-5'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[2],
  },
  {
    id: 'prod-4',
    category_id: 'cat-1',
    name: 'Pro Self-Leveling Epoxy Underlayment (20kg)',
    slug: 'self-leveling-epoxy-underlayment',
    description: 'Precision self-leveling epoxy mortar for smoothing uneven concrete surfaces prior to applying decorative or protective epoxy topcoats.',
    short_description: 'Self-leveling epoxy mortar for substrate preparation.',
    price: 11200,
    unit: 'Kit',
    image_url: 'https://images.unsplash.com/photo-1503387762-592deb587942?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [],
    featured: false,
    in_stock: true,
    display_order: 4,
    is_active: true,
    brand_id: null,
    sku: 'PRO-SL-20K',
    meta_title: 'Pro Self-Leveling Epoxy Mortar',
    meta_description: 'Precision self-leveling mortar for floor leveling.',
    stock_quantity: 25,
    low_stock_threshold: 5,
    related_products: ['prod-1'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'prod-5',
    category_id: 'cat-4',
    name: 'Pro Polyurethane Expansion Joint Sealant (600ml)',
    slug: 'polyurethane-expansion-joint-sealant',
    description: 'High-performance elastic polyurethane sealant for sealing movement and control joints in concrete floors, walls, and precast panels.',
    short_description: 'Elastic PU sealant for concrete expansion joints.',
    price: 2400,
    unit: 'Foil Pack',
    image_url: 'https://images.unsplash.com/photo-1615840728552-7073c8c5d6c5?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [],
    featured: false,
    in_stock: true,
    display_order: 5,
    is_active: true,
    brand_id: null,
    sku: 'PRO-PU-SEAL-600',
    meta_title: 'Pro PU Expansion Joint Sealant',
    meta_description: 'High elasticity joint sealant for concrete structures.',
    stock_quantity: 120,
    low_stock_threshold: 20,
    related_products: ['prod-3'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'prod-6',
    category_id: 'cat-5',
    name: 'Pro Lithium Concrete Hardener & Densifier (20L)',
    slug: 'lithium-concrete-hardener-densifier',
    description: 'Deeply penetrating lithium silicate chemical hardener that permanently seals and dustproofs concrete surfaces, enhancing abrasion resistance.',
    short_description: 'Penetrating lithium concrete hardener and dustproofer.',
    price: 12500,
    unit: 'Drum',
    image_url: 'https://images.unsplash.com/photo-1553413077-190083ec01ff?auto=format&fit=crop&w=800&q=80',
    gallery_urls: [],
    featured: true,
    in_stock: true,
    display_order: 6,
    is_active: true,
    brand_id: null,
    sku: 'PRO-LITH-20L',
    meta_title: 'Pro Lithium Concrete Densifier',
    meta_description: 'Penetrating concrete hardener for dustless floors.',
    stock_quantity: 35,
    low_stock_threshold: 8,
    related_products: [],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: MOCK_CATEGORIES[4],
  },
];

export const MOCK_HERO_SLIDES: HeroSlide[] = [
  {
    id: 'slide-1',
    title: 'Engineered Industrial & Commercial Flooring',
    subtitle: 'High-durability epoxy, polyurethane, and waterproofing systems built for heavy performance.',
    description: 'Trusted by manufacturing facilities, warehouses, commercial complexes, and food plants.',
    image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=1600&q=80',
    button_text: 'Explore Products',
    button_link: '/shop',
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'slide-2',
    title: 'Advanced Waterproofing Solutions',
    subtitle: 'Elastomeric membranes and crystalline waterproofing that withstand extreme conditions.',
    description: 'Protect roofs, basements, water tanks, and podium decks with guaranteed zero-leak performance.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1600&q=80',
    button_text: 'Request Quotation',
    button_link: '/quotation',
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'slide-3',
    title: 'Turnkey Application & Site Contracting',
    subtitle: 'Professional surface preparation, shot blasting, and certified installation services.',
    description: 'Our experienced technical team delivers flawless application backed by warranty and technical support.',
    image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1600&q=80',
    button_text: 'Our Services',
    button_link: '/services',
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-1',
    name: 'Industrial Epoxy Flooring Application',
    slug: 'industrial-epoxy-flooring',
    description: 'Comprehensive installation of heavy-duty, anti-slip, chemical-resistant epoxy floor systems for factories, distribution centers, and aircraft hangars.',
    short_description: 'Seamless chemical and wear-resistant epoxy floor installation.',
    image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=800&q=80',
    icon: 'ShieldCheck',
    features: ['Shot Blasting & Surface Prep', 'High Chemical Resistance', 'Anti-Static & Non-Slip Finishes', 'Full Warranty Coverage'],
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-2',
    name: 'Roof & Basement Waterproofing',
    slug: 'roof-basement-waterproofing',
    description: 'Complete leak diagnostic, surface treatment, and installation of elastomeric liquid polyurethane membranes or crystalline waterproofing for rooftops, retaining walls, and sub-structures.',
    short_description: 'Guaranteed zero-leak waterproofing for rooftops and basements.',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=800&q=80',
    icon: 'Droplets',
    features: ['Thermal Expansion Flexibility', 'Puddle-Proof UV Coatings', 'Root Barrier Protection', '10-Year Leak Assurance'],
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'srv-3',
    name: 'Concrete Polishing & Dustproofing',
    slug: 'concrete-polishing-dustproofing',
    description: 'Diamond grinding, hardener densification, and mechanical polishing of raw concrete floors to create mirror-like, dustless, low-maintenance polished concrete floors.',
    short_description: 'Diamond ground polished concrete floors with high reflectivity.',
    image_url: 'https://images.unsplash.com/photo-1553413077-190083ec01ff?auto=format&fit=crop&w=800&q=80',
    icon: 'Sparkles',
    features: ['Eliminates Concrete Dusting', 'Enhances Light Reflectivity', 'Low Lifetime Maintenance', 'Environmentally Friendly'],
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 't-1',
    name: 'John Miller',
    role: 'Operations Director',
    company: 'Metropolitan Logistics Hub',
    content: 'The flooring team transformed our 60,000 sq ft warehouse facility with a high-durability epoxy finish that withstands continuous heavy forklift operations.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    display_order: 1,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 't-2',
    name: 'Sarah Jenkins',
    role: 'Senior Property Manager',
    company: 'Capital Commercial Towers',
    content: 'Their elastomeric liquid waterproofing system completely solved active basement water seepage. Their technical team was prompt, professional, and thorough.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    display_order: 2,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 't-3',
    name: 'David Carter',
    role: 'Plant Manager',
    company: 'Apex Beverage Processing',
    content: 'The thermal-shock resistant PU mortar screed installed in our washdown bays has performed exceptionally well despite daily hot water washdowns.',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    rating: 5,
    display_order: 3,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_PARTNERS: Partner[] = [
  { id: 'p-1', name: 'Global Chemicals Inc', logo_url: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?auto=format&fit=crop&w=300&q=80', website_url: 'https://example.com', display_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: 'p-2', name: 'Master Building Solutions', logo_url: 'https://images.unsplash.com/photo-1516876437184-593fda40c7ce?auto=format&fit=crop&w=300&q=80', website_url: 'https://example.com', display_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: 'p-3', name: 'ProCoat Systems', logo_url: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&w=300&q=80', website_url: 'https://example.com', display_order: 3, is_active: true, created_at: new Date().toISOString() },
  { id: 'p-4', name: 'FlowResin Technologies', logo_url: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?auto=format&fit=crop&w=300&q=80', website_url: 'https://example.com', display_order: 4, is_active: true, created_at: new Date().toISOString() },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    title: 'Distribution Center Epoxy Floor Renovation',
    slug: 'distribution-center-epoxy-floor',
    client_name: 'Logistics Park Hub',
    service_type: 'Industrial Epoxy Flooring',
    category: 'Industrial',
    location: 'Metropolitan Logistics Zone',
    project_date: '2025-08-15',
    completion_date: '2025-09-01',
    project_value: 4500000,
    area_size: '8,500 sq meters',
    description: 'Complete shot blasting and heavy-duty 3mm epoxy self-leveling installation for a major regional logistics facility.',
    materials_used: 'Pro-Floor 3000 SL (Self-Leveling Resin), High-Build Moisture Barrier Primer, Quartz Silica Aggregates',
    challenge: 'Severely spalled concrete floor with oil contamination and tight 14-day turnaround requirement.',
    solution: 'Shot blasted surface to CSP 3-4, applied moisture barrier primer, and finished with high-build anti-slip epoxy.',
    results: 'Flawless dustless finish delivered 2 days ahead of schedule with 5-year commercial warranty.',
    featured: true,
    is_active: true,
    display_order: 1,
    images: [
      { id: 'img-1-1', project_id: 'proj-1', image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'High-gloss seamless epoxy floor', display_order: 1 },
      { id: 'img-1-2', project_id: 'proj-1', image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80', image_type: 'progress', caption: 'Surface grinding and primer application', display_order: 2 }
    ]
  },
  {
    id: 'proj-2',
    title: 'Food Processing Plant PU Screed Application',
    slug: 'food-plant-pu-screed',
    client_name: 'Dairy Processors Facility',
    service_type: 'Polyurethane Screed',
    category: 'Food & Beverage',
    location: 'Regional Industrial Park',
    project_date: '2025-11-10',
    completion_date: '2025-11-20',
    project_value: 3200000,
    area_size: '3,200 sq meters',
    description: 'Heavy-duty 6mm antimicrobial polyurethane screed for milk processing and cold storage rooms.',
    materials_used: 'Pro PolyScreed Heavy-Duty 600, Antimicrobial Polyurethane Cement Resin, Coved Wall Skirting Mortar',
    challenge: 'Continuous moisture exposure and thermal shock from 85°C steam washdowns.',
    solution: 'Heavy-duty PU mortar with coved skirting and integrated stainless steel drainage channels.',
    results: 'Achieved 100% compliance with international food hygiene standards and zero downtime.',
    featured: true,
    is_active: true,
    display_order: 2,
    images: [
      { id: 'img-2-1', project_id: 'proj-2', image_url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'Hygiene-certified heavy duty screed', display_order: 1 },
      { id: 'img-2-2', project_id: 'proj-2', image_url: 'https://images.unsplash.com/photo-1504307651674-208930a97d63?auto=format&fit=crop&w=1200&q=80', image_type: 'before', caption: 'Prior to application', display_order: 2 }
    ]
  },
  {
    id: 'proj-3',
    title: 'Commercial Complex Rooftop Waterproofing',
    slug: 'rooftop-waterproofing-project',
    client_name: 'Capital Plaza Towers',
    service_type: 'Waterproofing Systems',
    category: 'Commercial',
    location: 'Central Business District',
    project_date: '2025-06-01',
    completion_date: '2025-06-15',
    project_value: 2800000,
    area_size: '2,400 sq meters',
    description: 'Seamless liquid elastomeric polyurethane waterproofing membrane with UV-resistant topcoat applied on podium deck and roof.',
    challenge: 'Active rainfall leaks causing ceiling damage to high-end executive suites below.',
    solution: 'Pressure washed roof deck, sealed expansion joints, applied elastomeric polyurethane membrane with fleece reinforcement.',
    results: '100% leak-free performance tested with 48-hour flood ponding test.',
    materials_used: 'Pro HydroShield Polyurethane Elastomeric Liquid Membrane, UV-Stable Aliphatic Topcoat, Fleece Reinforcement Fabric',
    featured: true,
    is_active: true,
    display_order: 3,
    images: [
      { id: 'img-3-1', project_id: 'proj-3', image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'UV-resistant liquid elastomeric roof coating', display_order: 1 }
    ]
  },
  {
    id: 'proj-4',
    title: 'Luxury Car Showroom Polished Concrete',
    slug: 'luxury-showroom-polished-concrete',
    client_name: 'Prestige Motors Center',
    service_type: 'Concrete Polishing',
    category: 'Automotive & Retail',
    location: 'Metropolitan Commercial District',
    project_date: '2025-09-10',
    completion_date: '2025-09-22',
    project_value: 1950000,
    area_size: '1,500 sq meters',
    description: 'Diamond ground polished concrete floor with lithium silicate hardener and ultra-high gloss stain protection sealant.',
    challenge: 'Client needed a high-end mirror finish that withstands heavy vehicle tire marks without scuffing.',
    solution: '8-step diamond grinding process up to 3000 grit finish with penetrating lithium densifier.',
    results: 'Mirror-like reflective floor with zero tire marking and minimal maintenance needs.',
    materials_used: 'Pro Lithium Silicate Densifier, Diamond Grinding Pads (50 to 3000 grit), Stain Guard Penetrating Sealer',
    featured: true,
    is_active: true,
    display_order: 4,
    images: [
      { id: 'img-4-1', project_id: 'proj-4', image_url: 'https://images.unsplash.com/photo-1553413077-190083ec01ff?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'High-gloss polished concrete showroom floor', display_order: 1 }
    ]
  },
  {
    id: 'proj-5',
    title: 'Pharmaceutical Cleanroom Anti-Static Epoxy',
    slug: 'pharma-cleanroom-epoxy',
    client_name: 'Regional Pharma Ltd',
    service_type: 'ESD/Anti-Static Flooring',
    category: 'Healthcare & Pharma',
    location: 'Science & Technology Park',
    project_date: '2025-10-01',
    completion_date: '2025-10-14',
    project_value: 3800000,
    area_size: '2,100 sq meters',
    description: 'Conductive self-leveling ESD epoxy flooring system with copper grounding tape matrix for sterile cleanrooms.',
    challenge: 'Strict electrostatic discharge sensitivity and requirement for continuous radius wall coving.',
    solution: 'Installed grounding grid, conductive primer layer, and smooth seamless anti-static topcoat with coved joints.',
    results: 'Certified ESD safety resistance readings (10^6 to 10^8 ohms) and ISO cleanroom compliance.',
    materials_used: 'Pro Conductive ESD Epoxy Coating, Copper Grounding Matrix Tape, Wall-to-Floor Radius Coving Compound',
    featured: true,
    is_active: true,
    display_order: 5,
    images: [
      { id: 'img-5-1', project_id: 'proj-5', image_url: 'https://images.unsplash.com/photo-1503387762-592deb587942?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'Seamless anti-static cleanroom epoxy floor', display_order: 1 }
    ]
  },
  {
    id: 'proj-6',
    title: 'Aircraft Hangar Heavy Load Floor Coating',
    slug: 'aircraft-hangar-heavy-load-coating',
    client_name: 'Regional Aviation Hub',
    service_type: 'Industrial Epoxy Flooring',
    category: 'Aviation & Heavy Industry',
    location: 'International Airport Hub',
    project_date: '2025-07-01',
    completion_date: '2025-07-20',
    project_value: 5200000,
    area_size: '6,000 sq meters',
    description: 'Skydrol resistant polyurethane and epoxy hybrid coating capable of supporting aircraft point-loads and chemical spills.',
    challenge: 'Aviation hydraulic fluids destroy standard epoxy within hours.',
    solution: 'Specialized chemical-resistant aliphatic polyurethane topcoat over heavy-duty epoxy primer.',
    results: 'Outstanding chemical resilience and high visibility line markings for taxi lanes.',
    materials_used: 'Pro Skydrol-Guard Aliphatic Polyurethane Topcoat, High-Load Structural Epoxy Primer, Line Marking Polyurethane Enamel',
    featured: true,
    is_active: true,
    display_order: 6,
    images: [
      { id: 'img-6-1', project_id: 'proj-6', image_url: 'https://images.unsplash.com/photo-1615840728552-7073c8c5d6c5?auto=format&fit=crop&w=1200&q=80', image_type: 'after', caption: 'Chemical-resistant aircraft hangar floor', display_order: 1 }
    ]
  }
];

export const MOCK_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'dz-1',
    zone_name: 'Metropolitan Area',
    regions: ['Central District', 'Northside', 'West End', 'Industrial Zone', 'Eastside', 'South Hub'],
    base_charge: 1500,
    free_delivery_minimum: 50000,
    estimated_days: '1-2 business days',
    is_active: true,
    display_order: 1,
  },
  {
    id: 'dz-2',
    zone_name: 'Suburban Industrial Parks',
    regions: ['Logistics Valley', 'Agri Park', 'Tech Corridor', 'North Gateway'],
    base_charge: 2500,
    free_delivery_minimum: 75000,
    estimated_days: '2-3 business days',
    is_active: true,
    display_order: 2,
  },
  {
    id: 'dz-3',
    zone_name: 'Regional Destinations',
    regions: ['Northern Region', 'Southern Hub', 'Eastern Valley', 'Western Hub'],
    base_charge: 4500,
    free_delivery_minimum: 120000,
    estimated_days: '3-5 business days',
    is_active: true,
    display_order: 3,
  },
];
