BEGIN;
CREATE INDEX IF NOT EXISTS idx_privileged_access_requests_pending_expiry ON public.privileged_access_requests (status, expires_at) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_staff_identity_events_actor_type ON public.staff_identity_events (actor_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_staff_identity_events_user_type ON public.staff_identity_events (user_id, event_type, created_at DESC);
REVOKE ALL ON public.privileged_access_requests FROM anon;
REVOKE ALL ON public.staff_identity_events FROM anon;
REVOKE ALL ON public.staff_role_assignments FROM anon;
REVOKE ALL ON public.staff_role_permissions FROM anon;
REVOKE ALL ON public.staff_roles FROM anon;
REVOKE ALL ON public.staff_permissions FROM anon;
REVOKE ALL ON public.staff_profiles FROM anon;
REVOKE ALL ON public.staff_invitations FROM anon;
REVOKE ALL ON public.privileged_access_requests FROM PUBLIC;
REVOKE ALL ON public.staff_identity_events FROM PUBLIC;
REVOKE ALL ON public.staff_role_assignments FROM PUBLIC;
REVOKE ALL ON public.staff_role_permissions FROM PUBLIC;
REVOKE ALL ON public.staff_roles FROM PUBLIC;
REVOKE ALL ON public.staff_permissions FROM PUBLIC;
REVOKE ALL ON public.staff_profiles FROM PUBLIC;
REVOKE ALL ON public.staff_invitations FROM PUBLIC;
COMMIT;
