import { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, ClipboardCheck, DatabaseBackup, RefreshCw, Shield } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { createBusinessContinuityPlan, getBusinessContinuity360, recordRecoveryCheckpoint, recordRecoveryDrill, type ContinuitySnapshot } from '@/lib/business-continuity-360';

export default function BusinessContinuity360(){
 const [data,setData]=useState<ContinuitySnapshot|null>(null); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{setData(await getBusinessContinuity360())}catch(e){setMessage(e instanceof Error?e.message:'Unable to load continuity control.')}finally{setLoading(false)}},[]); useEffect(()=>{void load()},[load]);
 const create=async()=>{const title=window.prompt('Recovery plan title');if(!title?.trim())return;const domain=window.prompt('Domain','platform')??'platform';const criticality=window.prompt('Criticality: tier_1, tier_2, tier_3','tier_1')??'tier_1';const rto=Number(window.prompt('RTO minutes','60'));const rpo=Number(window.prompt('RPO minutes','60'));const procedure=window.prompt('Recovery procedure (minimum 20 characters)','Follow approved recovery runbook and verify customer-facing service before closure.')??'';try{await createBusinessContinuityPlan({title,domain,criticality,rtoMinutes:rto,rpoMinutes:rpo,recoveryProcedure:procedure});setMessage('Recovery plan recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create plan.')}};
 const drill=async(id:string)=>{const type=window.prompt('Drill type: tabletop, restore, failover, communications, full_recovery','tabletop')??'tabletop';try{await recordRecoveryDrill({planId:id,drillType:type,scheduledAt:new Date().toISOString()});setMessage('Recovery drill scheduled.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to schedule drill.')}};
 const checkpoint=async(id:string)=>{const type=window.prompt('Checkpoint: backup_evidence, restore_test, dependency_check, credential_recovery, contact_verification, runbook_review','runbook_review')??'runbook_review';const evidence=window.prompt('Evidence reference (optional)')??'';try{await recordRecoveryCheckpoint({planId:id,checkpointType:type,evidenceReference:evidence});setMessage('Recovery checkpoint recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to record checkpoint.')}};
 const m=data?.metrics;
 return <AdminLayout title="Business Continuity & Disaster Recovery 360" subtitle="Recovery readiness, RTO/RPO ownership, drills and evidence without claiming provider backups are application-owned." actions={<div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</button><button onClick={()=>void create()} className="rounded-lg bg-primary-600 px-3 py-2 text-sm font-medium text-white">Add recovery plan</button></div>}>
 {message&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm text-gray-700">{message}</div>}
 <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[['Plans',m?.plans],['Tier 1',m?.tier_1],['Active',m?.active],['Needs review',m?.needs_review],['Drills due',m?.drills_due],['Failed drills',m?.failed_drills]].map(([l,v])=><div key={l as string} className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">{l as string}</p><p className="mt-1 text-3xl font-semibold">{loading?'—':v??0}</p></div>)}</div>
 <section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><Shield className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Recovery plans</h2><p className="text-sm text-muted-foreground">Tier 1 services require explicit recovery targets and evidence.</p></div></div><div className="mt-5 space-y-3">{data?.plans.length?data.plans.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full border px-2 py-1 font-semibold uppercase">{p.criticality}</span><span className="rounded-full border px-2 py-1">{p.domain}</span><span className="rounded-full border px-2 py-1">RTO {p.rto_minutes}m</span><span className="rounded-full border px-2 py-1">RPO {p.rpo_minutes}m</span></div><p className="mt-2 font-medium">{p.title}</p><p className="mt-1 text-sm text-muted-foreground">Status: {p.status} · Latest drill: {p.latest_drill_status??'none'} · Latest checkpoint: {p.latest_checkpoint_at?new Date(p.latest_checkpoint_at).toLocaleString():'none'}</p></div><div className="flex gap-2"><button onClick={()=>void drill(p.id)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><ClipboardCheck className="h-4 w-4"/>Drill</button><button onClick={()=>void checkpoint(p.id)} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm"><DatabaseBackup className="h-4 w-4"/>Evidence</button></div></div></div>):<div className="flex items-center gap-2 py-8 text-sm text-muted-foreground"><CheckCircle2 className="h-4 w-4"/>No recovery plans recorded yet.</div>}</div></section>
 <section className="mt-6 rounded-2xl border bg-muted/30 p-5 text-sm text-muted-foreground"><div className="flex items-center gap-2 font-medium text-foreground"><DatabaseBackup className="h-4 w-4"/>Evidence boundary</div><p className="mt-2">Checkpoint records point to evidence; they do not certify that Supabase, Vercel or third-party providers completed a backup or restore. Real restore drills must be executed in an authorized environment and attached to the evidence trail.</p></section>
 </AdminLayout>
}
