import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Inbox, Mail, MessageCircle, RefreshCw, Send, Workflow } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { useToast } from '@/hooks/use-toast';
import { getCommunicationsJourney360, reconcileCommunications360, type CommunicationsJourney360 } from '@/lib/communications-journey-360';

const empty: CommunicationsJourney360 = { period_days: 30, metrics: {}, channels: [], recent_failures: [], unmatched_inbound: [], workflow_events: [] };
const n = (data: Record<string, number>, key: string) => data[key] ?? 0;

export default function AdminCommunicationsJourney360() {
  const [data, setData] = useState(empty);
  const [days, setDays] = useState(30);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const { toast } = useToast();
  const load = useCallback(async () => { setLoading(true); try { setData(await getCommunicationsJourney360(days)); } catch (e) { toast({ title:'Unable to load communications control plane', description:e instanceof Error?e.message:'Please try again', variant:'destructive' }); } finally { setLoading(false); } }, [days, toast]);
  useEffect(() => { void load(); }, [load]);
  const reconcile = async () => { setBusy(true); try { const r=await reconcileCommunications360(); toast({ title:'Communication queue reconciled', description:`Released ${Number(r.stale_locks_released||0)} stale locks.` }); await load(); } catch(e) { toast({ title:'Reconciliation failed', description:e instanceof Error?e.message:'Please try again', variant:'destructive' }); } finally { setBusy(false); } };
  const cards = [
    ['Queued','queued',Send], ['Pending delivery','pending_delivery',Workflow], ['Delivered','delivered',CheckCircle2], ['Delivery failures','delivery_failures',AlertTriangle],
    ['Stale queued','stale_queued',RefreshCw], ['Inbound replies','workflow_events',Inbox], ['Unmatched inbound','unmatched_inbound',MessageCircle], ['Suppressed workflows','suppressed_workflows',Mail],
  ] as const;
  return <AdminLayout title="Communications & Customer Journey 360" subtitle="One control plane from business event to customer preference, provider delivery, inbound response and operational action.">
    <div className="flex flex-wrap items-center justify-between gap-3 mb-6"><div><p className="eyebrow">Customer communication control</p><p className="text-sm text-muted-foreground">Durable outbox, channel preference, provider response and inbound matching are reconciled here.</p></div><div className="flex gap-2"><select className="h-10 border rounded-lg px-3 bg-white" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 days</option><option value={30}>30 days</option><option value={90}>90 days</option></select><button className="btn-secondary" onClick={()=>void reconcile()} disabled={busy}><RefreshCw className="w-4 h-4 mr-2"/>{busy?'Reconciling…':'Reconcile queue'}</button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6">{cards.map(([label,key,Icon])=><div className="surface p-5" key={key}><div className="flex items-center justify-between"><p className="eyebrow">{label}</p><Icon className="w-4 h-4 opacity-50"/></div><p className="text-2xl font-bold mt-2">{loading?'—':n(data.metrics,key)}</p></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-6">
      <section className="table-shell overflow-hidden"><div className="p-4 border-b"><p className="font-semibold">Channel performance</p><p className="text-sm text-muted-foreground">Outbound activity for the selected period.</p></div><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Channel</th><th>Total</th><th>Sent</th><th>Delivered</th><th>Failed</th></tr></thead><tbody>{data.channels.map((r,i)=><tr key={`${String(r.channel)}-${i}`}><td className="capitalize">{String(r.channel)}</td><td>{Number(r.total||0)}</td><td>{Number(r.sent||0)}</td><td>{Number(r.delivered||0)}</td><td>{Number(r.failed||0)}</td></tr>)}{!loading&&!data.channels.length&&<tr><td colSpan={5} className="p-8 text-center text-muted-foreground">No channel activity.</td></tr>}</tbody></table></div></section>
      <section className="table-shell overflow-hidden"><div className="p-4 border-b"><p className="font-semibold">Recent workflow events</p><p className="text-sm text-muted-foreground">Idempotent routing decisions connecting business events to the communication outbox.</p></div><div className="divide-y">{data.workflow_events.slice(0,10).map((r,i)=><div className="p-4 flex items-center justify-between gap-4" key={`${String(r.event_key)}-${i}`}><div><p className="text-sm font-medium">{String(r.event_type)}</p><p className="text-xs text-muted-foreground">{String(r.status)} · {Number(r.queued_count||0)} queued</p></div><span className="text-xs text-muted-foreground">{r.created_at?new Date(String(r.created_at)).toLocaleString():''}</span></div>)}{!loading&&!data.workflow_events.length&&<p className="p-8 text-center text-muted-foreground">No workflow events in this period.</p>}</div></section>
      <section className="table-shell overflow-hidden"><div className="p-4 border-b"><p className="font-semibold">Delivery failures</p><p className="text-sm text-muted-foreground">Provider or delivery failures requiring operational attention.</p></div><div className="divide-y">{data.recent_failures.slice(0,10).map((r,i)=><div className="p-4" key={`${String(r.id)}-${i}`}><div className="flex justify-between gap-3"><span className="text-xs uppercase font-semibold">{String(r.channel)}</span><span className="text-xs text-muted-foreground">{String(r.delivery_status||r.status)}</span></div><p className="text-sm mt-1">{String(r.recipient||'')}</p><p className="text-xs text-muted-foreground mt-1">{String(r.error_message||'Provider delivery failed')}</p></div>)}{!loading&&!data.recent_failures.length&&<p className="p-8 text-center text-muted-foreground">No recent delivery failures.</p>}</div></section>
      <section className="table-shell overflow-hidden"><div className="p-4 border-b"><p className="font-semibold">Unmatched inbound responses</p><p className="text-sm text-muted-foreground">Responses that could not yet be associated with a customer record.</p></div><div className="divide-y">{data.unmatched_inbound.slice(0,10).map((r,i)=><div className="p-4" key={`${String(r.id)}-${i}`}><div className="flex justify-between gap-3"><span className="text-xs uppercase font-semibold">{String(r.channel)}</span><span className="text-xs text-muted-foreground">{r.received_at?new Date(String(r.received_at)).toLocaleString():''}</span></div><p className="text-sm mt-1">{String(r.sender||'')}</p><p className="text-xs text-muted-foreground mt-1 line-clamp-2">{String(r.message||'')}</p></div>)}{!loading&&!data.unmatched_inbound.length&&<p className="p-8 text-center text-muted-foreground">All recent inbound responses are matched.</p>}</div></section>
    </div>
  </AdminLayout>;
}
