import {useCallback,useEffect,useState} from 'react';
import {CheckCircle2,Database,RefreshCw,ShieldCheck,UserCheck} from 'lucide-react';
import {AdminLayout} from './dashboard';
import {createDataGovernancePolicy,createDataSubjectRequest,completeDataSubjectRequest,getDataGovernance360,type GovernanceSnapshot} from '@/lib/data-governance-360';
export default function DataGovernance360(){const [data,setData]=useState<GovernanceSnapshot|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);setMessage('');try{setData(await getDataGovernance360())}catch(e){setMessage(e instanceof Error?e.message:'Unable to load data governance control.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const addPolicy=async()=>{const title=window.prompt('Policy title');if(!title?.trim())return;const domain=window.prompt('Domain: customers, orders, finance, projects, inventory, communications, staff, content, system, other','customers')??'customers';const classification=window.prompt('Classification: public, internal, confidential, restricted','confidential')??'confidential';const days=Number(window.prompt('Retention days','365'));const handling=window.prompt('Handling requirements (minimum 10 characters)','Limit access to authorized staff and preserve audit evidence.')??'';try{await createDataGovernancePolicy({domain,classification,title,retentionDays:days,handlingRequirements:handling});setMessage('Governance policy recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create policy.')}};
const addRequest=async()=>{const type=window.prompt('Request type: access, correction, deletion, restriction, portability, objection','access')??'access';const due=new Date(Date.now()+14*86400000).toISOString();try{await createDataSubjectRequest({requestType:type,dueAt:due});setMessage('Data-subject request recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create request.')}};
const complete=async(id:string)=>{const resolution=window.prompt('Resolution / outcome');if(!resolution?.trim())return;try{await completeDataSubjectRequest(id,'completed',resolution);setMessage('Request completed with evidence trail.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete request.')}};const m=data?.metrics;return <AdminLayout title="Data Governance & Privacy 360" subtitle="Classification, retention controls, data-subject requests and periodic staff access review evidence." actions={<div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</button><button onClick={()=>void addPolicy()} className="rounded-lg bg-primary-600 px-3 py-2 text-sm font-medium text-white">Add policy</button><button onClick={()=>void addRequest()} className="rounded-lg border px-3 py-2 text-sm">Record request</button></div>}>
{message&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm text-gray-700">{message}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-7">{[['Policies',m?.policies],['Restricted',m?.restricted],['Needs review',m?.needs_review],['Open requests',m?.open_requests],['Overdue requests',m?.overdue_requests],['Overdue access reviews',m?.overdue_access_reviews],['Reviews 90d',m?.completed_access_reviews_90d]].map(([l,v])=><div key={l as string} className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">{l as string}</p><p className="mt-1 text-3xl font-semibold">{loading?'—':v??0}</p></div>)}</div>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><Database className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Governance policies</h2><p className="text-sm text-muted-foreground">Every sensitive data domain has an owner, classification, retention target and review date.</p></div></div><div className="mt-5 space-y-3">{data?.policies.length?data.policies.map(p=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full border px-2 py-1 font-semibold uppercase">{p.classification}</span><span className="rounded-full border px-2 py-1">{p.domain}</span><span className="rounded-full border px-2 py-1">{p.retention_days} days</span></div><p className="mt-2 font-medium">{p.title}</p><p className="mt-1 text-sm text-muted-foreground">Status: {p.status} · Review: {p.next_review_at?new Date(p.next_review_at).toLocaleDateString():'not scheduled'}</p></div>):<div className="py-8 text-sm text-muted-foreground">No governance policies recorded yet.</div>}</div></section>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Open data-subject requests</h2><p className="text-sm text-muted-foreground">Requests remain visible until an explicit outcome and evidence reference are recorded.</p></div></div><div className="mt-5 space-y-3">{data?.open_requests.length?data.open_requests.map(r=><div key={r.id} className="rounded-xl border p-4 flex items-center justify-between gap-3"><div><p className="font-medium capitalize">{r.request_type} request</p><p className="text-sm text-muted-foreground">Due {new Date(r.due_at).toLocaleString()} · {r.status}</p></div><button onClick={()=>void complete(r.id)} className="rounded-lg border px-3 py-2 text-sm">Complete</button></div>):<div className="flex items-center gap-2 py-8 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>No open data-subject requests.</div>}</div></section>
<section className="mt-6 rounded-2xl border bg-muted/30 p-5 text-sm text-muted-foreground"><div className="flex items-center gap-2 font-medium text-foreground"><UserCheck className="h-4 w-4"/>Control boundary</div><p className="mt-2">These records establish governance and evidence. They do not automatically delete customer data, change staff roles, or override Supabase/provider retention policies.</p></section>
</AdminLayout>}
