import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, MapPin, RefreshCw, Truck, UserRound } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';
import { assignDeliveryDriver, getActiveDeliveryDrivers, getFulfillmentDelivery360, markDeliveryPicked, recordDeliveryException, recoverFailedDelivery, rescheduleDelivery } from '@/lib/fulfillment-delivery-360';

type Row = { id:string; order_id:string; tracking_number:string|null; status:string; scheduled_date:string|null; driver_name:string|null; assigned_driver_user_id:string|null; failed_reason:string|null; picked_at:string|null; order?:{order_number:string|null;customer_name:string|null;customer_phone:string|null;payment_status:string|null;delivery_address:string|null}|null };
const n=(v:unknown)=>Number(v||0).toLocaleString();
export default function AdminFulfillmentDelivery360(){
 const [data,setData]=useState<Record<string,unknown>>({}); const [rows,setRows]=useState<Row[]>([]); const [drivers,setDrivers]=useState<Array<{user_id:string;display_name:string;phone:string|null}>>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<string|null>(null); const {toast}=useToast();
 const load=useCallback(async()=>{setLoading(true);try{const [snapshot,deliveryRows,driverRows]=await Promise.all([getFulfillmentDelivery360(30),supabase.from('deliveries').select('id,order_id,tracking_number,status,scheduled_date,driver_name,assigned_driver_user_id,failed_reason,picked_at,order:orders(order_number,customer_name,customer_phone,payment_status,delivery_address)').order('created_at',{ascending:false}),getActiveDeliveryDrivers()]);if(deliveryRows.error)throw deliveryRows.error;setData(snapshot);setRows((deliveryRows.data || []).map((row) => ({ ...row, order: Array.isArray(row.order) ? row.order[0] ?? null : row.order ?? null })) as Row[]);setDrivers(driverRows);}catch(e){toast({title:'Fulfillment snapshot failed',description:e instanceof Error?e.message:'Unable to load operations',variant:'destructive'});}finally{setLoading(false);}},[toast]);
 useEffect(()=>{void load()},[load]);
 const run=async(key:string,fn:()=>Promise<unknown>,title:string)=>{setBusy(key);try{await fn();toast({title});await load();}catch(e){toast({title:'Fulfillment action failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'});}finally{setBusy(null)}};
 const cards: Array<[string, unknown]>=[['Paid orders',data.orders_paid],['Processing',data.processing],['Dispatched',data.dispatched],['In transit',data.in_transit],['Delivered',data.delivered],['Overdue',data.overdue],['Unassigned',data.unassigned],['Exceptions',data.exceptions]];
 return <AdminLayout title="Fulfillment & Delivery 360" subtitle="Control the complete path from paid order readiness through dispatch, tracking, proof of delivery and exception recovery.">
  <div className="flex justify-end mb-5"><button className="btn-secondary flex items-center gap-2" onClick={()=>void load()} disabled={loading}><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/>Refresh</button></div>
  <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-8 gap-3">{cards.map(([label,value])=><div className="surface p-4" key={String(label)}><p className="eyebrow">{label}</p><p className="text-2xl font-bold mt-1">{loading?'—':n(value)}</p></div>)}</div>
  <div className="surface mt-5 p-5"><div className="flex items-center gap-2"><Truck className="w-5 h-5"/><h2 className="font-bold">Delivery control queue</h2></div><p className="text-sm text-muted-foreground mt-1">Dispatch requires a paid order, delivery address and an active assigned driver. Exceptions remain visible until recovered.</p>
   <div className="table-shell mt-4 overflow-x-auto"><table className="w-full"><thead><tr><th>Tracking</th><th>Order / customer</th><th>Status</th><th>Schedule</th><th>Driver</th><th>Payment</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-8 text-center">Loading…</td></tr>:rows.length?rows.map(r=><tr key={r.id}><td className="font-mono text-xs">{r.tracking_number||'—'}</td><td>{r.order?.order_number||r.order_id.slice(0,8)}<div className="text-xs text-muted-foreground">{r.order?.customer_name||'—'}</div></td><td><span className="chip">{r.status.replace('_',' ')}</span>{r.failed_reason&&<div className="text-xs text-destructive mt-1">{r.failed_reason}</div>}</td><td>{r.scheduled_date||<span className="text-amber-600">Unscheduled</span>}</td><td><div className="flex items-center gap-2"><UserRound className="w-4 h-4"/><select className="input min-w-[160px]" value={r.assigned_driver_user_id||''} onChange={e=>e.target.value&&void run(`assign-${r.id}`,()=>assignDeliveryDriver(r.id,e.target.value),'Driver assigned')} disabled={busy===`assign-${r.id}`}><option value="">Assign driver…</option>{drivers.map(d=><option key={d.user_id} value={d.user_id}>{d.display_name}</option>)}</select></div></td><td>{r.order?.payment_status||'—'}</td><td><div className="flex flex-wrap gap-2">{['pending','processing'].includes(r.status)&&<button className="btn-secondary" onClick={()=>void run(`pick-${r.id}`,()=>markDeliveryPicked(r.id),'Marked picked')}>Picked</button>}{r.status==='failed'&&<button className="btn-secondary" onClick={()=>void run(`recover-${r.id}`,()=>recoverFailedDelivery(r.id),'Exception recovered')}>Recover</button>}{!['delivered','cancelled'].includes(r.status)&&<button className="btn-secondary" onClick={()=>{const date=window.prompt('New delivery date (YYYY-MM-DD)',r.scheduled_date||'');if(date)void run(`reschedule-${r.id}`,()=>rescheduleDelivery(r.id,date),'Delivery rescheduled')}}>Reschedule</button>}{!['delivered','cancelled','failed'].includes(r.status)&&<button className="btn-secondary" onClick={()=>{const reason=window.prompt('Exception reason');if(reason)void run(`exception-${r.id}`,()=>recordDeliveryException(r.id,reason),'Delivery exception recorded')}}><AlertTriangle className="w-4 h-4"/></button>}</div></td></tr>):<tr><td colSpan={7} className="p-10 text-center text-muted-foreground">No deliveries in the operational queue.</td></tr>}</tbody></table></div></div>
  <div className="grid lg:grid-cols-3 gap-4 mt-5"><div className="surface-soft p-5"><CheckCircle2 className="w-5 h-5"/><h3 className="font-semibold mt-3">Readiness</h3><p className="text-sm text-muted-foreground mt-1">Payment, inventory conversion and delivery address are checked server-side before fulfillment begins.</p></div><div className="surface-soft p-5"><Clock3 className="w-5 h-5"/><h3 className="font-semibold mt-3">Control points</h3><p className="text-sm text-muted-foreground mt-1">Assignment, picking, scheduling, dispatch and transit changes are auditable lifecycle events.</p></div><div className="surface-soft p-5"><MapPin className="w-5 h-5"/><h3 className="font-semibold mt-3">Customer tracking</h3><p className="text-sm text-muted-foreground mt-1">Public tracking remains privacy-bounded and uses the canonical order and delivery state.</p></div></div>
 </AdminLayout>;
}
