import {useCallback,useEffect,useState} from 'react';
import {AlertTriangle,HardHat,RefreshCw,ShieldCheck} from 'lucide-react';
import {AdminLayout} from './dashboard';
import {createHseCorrectiveAction360,createHseSiteControl360,createHseSiteEvent360,getHseSiteCompliance360,updateHseCorrectiveAction360,updateHseEvent360,type HseSnapshot} from '@/lib/hse-site-compliance-360';
const val=(x:unknown)=>String(x??'—');
export default function HseSiteCompliance360(){const [data,setData]=useState<HseSnapshot|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);try{setData(await getHseSiteCompliance360());setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to load HSE controls.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const newSite=async()=>{const title=window.prompt('Site control title');if(!title?.trim())return;const siteName=window.prompt('Site name');if(!siteName?.trim())return;const risk=window.prompt('Risk: low, medium, high, critical','medium')||'medium';try{await createHseSiteControl360({title,siteName,riskLevel:risk});setMessage('Site control created.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create site control.')}};
const newEvent=async(id:string)=>{const description=window.prompt('Hazard / observation / incident description');if(!description?.trim())return;const type=window.prompt('Type: hazard, near_miss, incident, observation, toolbox_talk','hazard')||'hazard';const severity=window.prompt('Severity: low, medium, high, critical','medium')||'medium';try{await createHseSiteEvent360({controlId:id,eventType:type,severity,description});setMessage('HSE event recorded.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to record HSE event.')}};
const eventAdvance=async(e:Record<string,unknown>)=>{const s=val(e.status);const next=s==='open'?'investigating':s==='investigating'?'controlled':s==='controlled'?'resolved':'closed';try{await updateHseEvent360(val(e.id),next);setMessage(`Event ${next}.`);await load()}catch(x){setMessage(x instanceof Error?x.message:'Unable to update event.')}};
const actionAdvance=async(a:Record<string,unknown>)=>{const s=val(a.status);const next=s==='open'?'in_progress':s==='in_progress'?'completed':s==='completed'?'verified':'closed';const notes=next==='verified'||next==='closed'?window.prompt('Verification notes (minimum 10 characters)'):undefined;if((next==='verified'||next==='closed')&&!notes?.trim())return;try{await updateHseCorrectiveAction360(val(a.id),next,notes);setMessage(`Corrective action ${next}.`);await load()}catch(x){setMessage(x instanceof Error?x.message:'Unable to update action.')}};
const addAction=async(id:string)=>{const plan=window.prompt('Corrective action plan (minimum 10 characters)');if(!plan?.trim())return;try{await createHseCorrectiveAction360({eventId:id,actionPlan:plan});setMessage('Corrective action created.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create action.')}};
const m=data?.metrics||{};return <AdminLayout title="Health, Safety & Site Compliance 360" subtitle="Site controls, hazards, incidents and verified corrective actions." actions={<button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</button>}>
{message&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm">{message}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[['Sites',m.sites_total],['High risk',m.high_risk_sites],['Open events',m.open_events],['Critical events',m.critical_events],['Overdue actions',m.overdue_actions],['Reviews due',m.review_due_sites]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">{String(l)}</p><p className="mt-1 text-3xl font-semibold">{loading?'—':Number(v||0)}</p></div>)}</div><div className="mt-6 flex justify-end"><button onClick={()=>void newSite()} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">New site control</button></div>
<section className="mt-4 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><HardHat className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Site controls</h2><p className="text-sm text-muted-foreground">Risk, induction, PPE and review posture.</p></div></div><div className="mt-5 space-y-3">{data?.sites.map(s=><div key={val(s.id)} className="rounded-xl border p-4 flex flex-wrap justify-between gap-3"><div><p className="font-medium">{val(s.title)}</p><p className="text-sm text-muted-foreground">{val(s.site_name)} · {val(s.risk_level)} · {val(s.status)}</p><p className="text-sm">Induction: {val(s.induction_required)} · review {s.review_due_at?new Date(String(s.review_due_at)).toLocaleDateString():'not set'}</p></div><button onClick={()=>void newEvent(val(s.id))} disabled={val(s.status)!=='active'} className="rounded-lg border px-3 py-2 text-sm">Record event</button></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Open HSE events</h2><p className="text-sm text-muted-foreground">Events progress from detection through control and resolution.</p></div></div><div className="mt-5 space-y-3">{data?.events.map(e=><div key={val(e.id)} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{val(e.control_title)} · {val(e.event_type)} · {val(e.severity)}</p><p className="mt-1 text-sm">{val(e.description)}</p><p className="text-sm text-muted-foreground">{val(e.status)} · {new Date(String(e.occurred_at)).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={()=>void addAction(val(e.id))} className="rounded-lg border px-3 py-2 text-sm">Add action</button><button onClick={()=>void eventAdvance(e)} className="rounded-lg border px-3 py-2 text-sm">Advance</button></div></div></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Corrective actions</h2><p className="text-sm text-muted-foreground">Verification evidence is required before closure.</p></div></div><div className="mt-5 space-y-3">{data?.actions.length?data.actions.map(a=><div key={val(a.id)} className="rounded-xl border p-4 flex flex-wrap justify-between gap-3"><div><p className="font-medium">{val(a.status)} · due {a.due_at?new Date(String(a.due_at)).toLocaleString():'not set'}</p><p className="text-sm">{val(a.action_plan)}</p><p className="text-sm text-muted-foreground">{val(a.event_description)}</p></div><button onClick={()=>void actionAdvance(a)} className="rounded-lg border px-3 py-2 text-sm">Advance</button></div>):<div className="py-6 text-sm">No open HSE corrective actions.</div>}</div></section>
</AdminLayout>}
