import {useCallback,useEffect,useState} from 'react';
import {CheckCircle2,RefreshCw,Shield,UserCheck,UserX} from 'lucide-react';
import {AdminLayout} from './dashboard';
import {changeStaffStatus,decidePrivilegedAccessRequest,getIdentityAccess360,type IdentitySnapshot} from '@/lib/identity-access-360';
export default function IdentityAccess360(){const [data,setData]=useState<IdentitySnapshot|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);try{setData(await getIdentityAccess360());setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to load identity controls.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const toggle=async(s:IdentitySnapshot['staff'][number])=>{const reason=window.prompt(`${s.is_active?'Deactivate':'Activate'} ${s.display_name||s.user_id}? Reason (minimum 10 characters)`);if(!reason?.trim())return;try{await changeStaffStatus(s.user_id,!s.is_active,reason);setMessage(`Staff member ${s.is_active?'deactivated':'activated'}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to change staff status.')}};
const decide=async(id:string,status:'approved'|'rejected')=>{const notes=window.prompt(`${status==='approved'?'Approval':'Rejection'} notes (minimum 10 characters)`);if(!notes?.trim())return;try{await decidePrivilegedAccessRequest(id,status,notes);setMessage(`Access request ${status}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to decide access request.')}};
const m=data?.metrics;return <AdminLayout title="Identity & Privileged Access 360" subtitle="Controlled staff lifecycle, role-change evidence and elevated-access approvals." actions={<button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</button>}>
{message&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm">{message}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{[['Active staff',m?.active_staff],['Inactive staff',m?.inactive_staff],['Pending access',m?.pending_privileged_requests],['Expiring access',m?.expiring_privileged_requests],['Identity events 30d',m?.identity_events_30d]].map(([l,v])=><div key={l as string} className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">{l as string}</p><p className="mt-1 text-3xl font-semibold">{loading?'—':v??0}</p></div>)}</div>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><UserCheck className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Staff access posture</h2><p className="text-sm text-muted-foreground">Status changes are reasoned, authorized and recorded as identity evidence.</p></div></div><div className="mt-5 space-y-3">{data?.staff.map(s=><div key={s.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-medium">{s.display_name||s.user_id.slice(0,8)}</p><p className="text-sm text-muted-foreground">{s.job_title||'Staff'} · {s.roles.join(', ')||'No roles'}</p></div><button onClick={()=>void toggle(s)} className="rounded-lg border px-3 py-2 text-sm">{s.is_active?'Deactivate':'Activate'}</button></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><Shield className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Pending privileged access</h2><p className="text-sm text-muted-foreground">Elevated roles require an explicit decision and evidence.</p></div></div><div className="mt-5 space-y-3">{data?.pending_requests.length?data.pending_requests.map(r=><div key={String(r.id)} className="rounded-xl border p-4"><p className="font-medium">{String(r.role_code)} · {String(r.requested_user_id).slice(0,8)}</p><p className="mt-1 text-sm text-muted-foreground">{String(r.reason)}</p><div className="mt-3 flex gap-2"><button onClick={()=>void decide(String(r.id),'approved')} className="rounded-lg border px-3 py-2 text-sm">Approve</button><button onClick={()=>void decide(String(r.id),'rejected')} className="rounded-lg border px-3 py-2 text-sm">Reject</button></div></div>):<div className="flex items-center gap-2 py-6 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>No pending privileged-access requests.</div>}</div></section>
<section className="mt-6 rounded-2xl border bg-muted/30 p-5 text-sm text-muted-foreground"><div className="flex items-center gap-2 font-medium text-foreground"><UserX className="h-4 w-4"/>Security boundary</div><p className="mt-2">This controls Topline business authorization and evidence. Supabase Auth remains the authentication authority; MFA, session policy and provider-level identity settings still require configuration and verification in the real production environment.</p></section>
</AdminLayout>}
