import { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { assignInstallationStaff, updateInstallationStatus, removeInstallationAssignment } from '@/lib/field-operations';
import { useToast } from '@/hooks/use-toast';
import { CalendarDays, Users, Play, CheckCircle2, UserPlus, X } from 'lucide-react';

export default function InstallationWorkforce() {
  const [installations,setInstallations]=useState<any[]>([]); const [staff,setStaff]=useState<any[]>([]); const [assignments,setAssignments]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<any>(null); const [staffId,setStaffId]=useState(''); const [role,setRole]=useState('installer'); const {toast}=useToast();
  const load=useCallback(async()=>{setLoading(true); const [i,s,a]=await Promise.all([supabase.from('installations').select('id,installation_number,project_id,scheduled_date,scheduled_time,status,notes,projects(title,client_name)').order('scheduled_date',{ascending:true}),supabase.from('staff_profiles').select('user_id,display_name,email,is_active').eq('is_active',true).order('display_name'),supabase.from('installation_assignments').select('*').neq('status','removed').order('created_at',{ascending:false})]); setInstallations(i.data||[]);setStaff(s.data||[]);setAssignments(a.data||[]);setLoading(false);},[]);
  useEffect(()=>{void load();},[load]);
  const run=async(fn:()=>Promise<any>,title:string)=>{try{await fn();toast({title});await load();}catch(e){toast({title:'Action failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'});}};
  return <AdminLayout title="Installation Workforce" subtitle="Schedule field teams, control installation status and keep responsibility visible.">
    <div className="grid gap-4 sm:grid-cols-4 mb-6">{['scheduled','in_progress','completed','rescheduled'].map(s=><div className="surface p-5" key={s}><p className="eyebrow">{s.replace('_',' ')}</p><p className="text-2xl font-bold mt-2">{installations.filter(x=>x.status===s).length}</p></div>)}</div>
    <div className="grid xl:grid-cols-[1.25fr_.75fr] gap-6"><section className="table-shell overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Installation</th><th>Project</th><th>Date</th><th>Status</th><th>Team</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center">Loading…</td></tr>:installations.map(i=><tr key={i.id}><td className="font-mono">{i.installation_number||i.id.slice(0,8)}</td><td>{i.projects?.title||'—'}<div className="text-xs text-muted-foreground">{i.projects?.client_name||''}</div></td><td>{i.scheduled_date||'Unscheduled'}</td><td><span className="chip">{i.status}</span></td><td>{assignments.filter(a=>a.installation_id===i.id&&a.status!=='removed').length}</td><td><button className="btn-secondary" onClick={()=>setSelected(i)}>Manage</button></td></tr>)}{!loading&&!installations.length&&<tr><td colSpan={6} className="p-10 text-center text-muted-foreground">No installations scheduled.</td></tr>}</tbody></table></div></section>
      <aside className="surface p-6">{selected?<><div className="flex items-start justify-between"><div><p className="eyebrow">{selected.installation_number||'Installation'}</p><h2 className="text-xl font-bold mt-1">{selected.projects?.title||'Project installation'}</h2></div><button onClick={()=>setSelected(null)}><X className="w-5 h-5"/></button></div><div className="mt-5 grid gap-3"><label className="text-sm font-medium">Assign active staff<select className="input mt-1 w-full" value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Select staff member</option>{staff.map(s=><option key={s.user_id} value={s.user_id}>{s.display_name||s.email}</option>)}</select></label><label className="text-sm font-medium">Role<select className="input mt-1 w-full" value={role} onChange={e=>setRole(e.target.value)}><option value="lead_installer">Lead installer</option><option value="installer">Installer</option><option value="technician">Technician</option><option value="supervisor">Supervisor</option><option value="helper">Helper</option></select></label><button className="btn-primary" disabled={!staffId} onClick={()=>run(()=>assignInstallationStaff({installationId:selected.id,staffUserId:staffId,role}),'Staff assigned')}><UserPlus className="w-4 h-4 mr-2 inline"/>Assign Team Member</button></div><div className="mt-6"><p className="font-semibold">Current team</p><div className="mt-3 space-y-2">{assignments.filter(a=>a.installation_id===selected.id&&a.status!=='removed').map(a=><div className="flex items-center justify-between border rounded-lg p-3" key={a.id}><span className="text-sm">{staff.find(s=>s.user_id===a.staff_user_id)?.display_name||a.staff_user_id.slice(0,8)} · {a.assignment_role}</span><button className="text-red-600" onClick={()=>run(()=>removeInstallationAssignment(a.id),'Assignment removed')}><X className="w-4 h-4"/></button></div>)}{assignments.filter(a=>a.installation_id===selected.id&&a.status!=='removed').length===0&&<p className="text-sm text-muted-foreground">No staff assigned.</p>}</div></div><div className="mt-6 flex flex-wrap gap-2">{selected.status==='scheduled'&&<button className="btn-primary" onClick={()=>run(()=>updateInstallationStatus(selected.id,'in_progress'),'Installation started')}><Play className="w-4 h-4 mr-1 inline"/>Start</button>}{selected.status==='in_progress'&&<button className="btn-primary" onClick={()=>run(()=>updateInstallationStatus(selected.id,'completed'),'Installation completed')}><CheckCircle2 className="w-4 h-4 mr-1 inline"/>Complete</button>}<div className="text-sm text-muted-foreground flex items-center gap-1 ml-auto"><CalendarDays className="w-4 h-4"/>{selected.scheduled_date||'No date'}</div></div></>:<div className="py-16 text-center text-muted-foreground"><Users className="w-10 h-10 mx-auto mb-3 opacity-50"/><p>Select an installation to manage its field team.</p></div>}</aside></div>
  </AdminLayout>;
}
