import { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from './dashboard';
import { useToast } from '@/hooks/use-toast';
import { CalendarClock, CheckCircle2, PauseCircle, PlayCircle, ShieldCheck } from 'lucide-react';
import { getMaintenanceOperations360, completeMaintenanceVisit360, transitionMaintenancePlan360 } from '@/lib/maintenance-operations-360';
import type { RpcResult } from '@/lib/types';

type Row = Record<string, RpcResult>;
export default function AdminMaintenancePlans(){
  const [data,setData]=useState<{metrics:Record<string,number>;plans:Row[];upcoming_visits:Row[]}>({metrics:{},plans:[],upcoming_visits:[]});
  const [loading,setLoading]=useState(true); const {toast}=useToast();
  const load=useCallback(async()=>{setLoading(true);try{setData(await getMaintenanceOperations360())}catch(e){toast({title:'Unable to load maintenance operations',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}finally{setLoading(false)}},[toast]);
  useEffect(()=>{void load()},[load]);
  const act=async(fn:()=>Promise<unknown>,title:string)=>{try{await fn();toast({title});await load()}catch(e){toast({title:'Action failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}};
  return <AdminLayout title="Maintenance Plans" subtitle="Preventive maintenance, scheduled visits and renewal readiness across completed customer work.">
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5 mb-6">{[['Active plans','active_plans'],['Due in 30 days','due_30_days'],['Overdue','overdue'],['Expiring in 60 days','expiring_60_days'],['Paused','paused_plans']].map(([label,key])=><div className="surface p-5" key={key}><p className="eyebrow">{label}</p><p className="text-2xl font-bold mt-2">{data.metrics[key]??0}</p></div>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.5fr_1fr]">
      <div className="table-shell overflow-hidden"><div className="p-4 border-b"><p className="font-semibold">Maintenance portfolio</p><p className="text-sm text-muted-foreground">Server-authoritative plan status and next service date.</p></div><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Plan</th><th>Customer</th><th>Frequency</th><th>Next due</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-8 text-center">Loading…</td></tr>:data.plans.map(p=><tr key={p.id}><td><div className="font-medium">{p.name}</div><div className="text-xs text-muted-foreground font-mono">{p.plan_number}</div></td><td>{p.customer_name}<div className="text-xs text-muted-foreground">{p.customer_phone||p.customer_email||''}</div></td><td>Every {p.frequency_months} mo.</td><td className={p.next_due_on&&p.next_due_on<new Date().toISOString().slice(0,10)?'font-semibold':''}>{p.next_due_on||'—'}</td><td><span className="chip">{p.status}</span></td><td className="flex gap-2 py-3">{p.status==='active'&&<button className="btn-secondary" onClick={()=>void act(()=>transitionMaintenancePlan360(p.id,'paused'),'Plan paused')}><PauseCircle className="w-4 h-4"/></button>}{p.status==='paused'&&<button className="btn-secondary" onClick={()=>void act(()=>transitionMaintenancePlan360(p.id,'active'),'Plan reactivated')}><PlayCircle className="w-4 h-4"/></button>}{!['cancelled','completed'].includes(p.status)&&<button className="btn-secondary" onClick={()=>void act(()=>transitionMaintenancePlan360(p.id,'completed'),'Plan completed')}><CheckCircle2 className="w-4 h-4"/></button>}</td></tr>)}{!loading&&!data.plans.length&&<tr><td colSpan={6} className="p-10 text-center text-muted-foreground"><ShieldCheck className="w-10 h-10 mx-auto mb-3 opacity-50"/>No maintenance plans yet.</td></tr>}</tbody></table></div></div>
      <div className="surface p-5"><div className="flex items-center gap-2 mb-4"><CalendarClock className="w-5 h-5"/><div><p className="font-semibold">Upcoming visits</p><p className="text-sm text-muted-foreground">Scheduled preventive work.</p></div></div><div className="space-y-3">{data.upcoming_visits.map(v=><div className="border rounded-lg p-3" key={v.id}><p className="font-medium">{v.plan_name}</p><p className="text-sm">{v.customer_name}</p><p className="text-xs text-muted-foreground mt-1">{v.scheduled_for} · {v.status}</p>{v.status==='in_progress'&&<button className="btn-primary mt-3" onClick={()=>void act(()=>completeMaintenanceVisit360(v.id),'Visit completed')}>Complete visit</button>}</div>)}{!data.upcoming_visits.length&&<p className="text-sm text-muted-foreground">No upcoming visits.</p>}</div></div>
    </div>
  </AdminLayout>;
}
