import { useCallback, useEffect, useState } from 'react';
import { Plus, Save, Trash2, ArrowUp, ArrowDown } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';

type Page = { id:string; slug:string; title:string; seo_title:string|null; seo_description:string|null; status:'draft'|'published'|'archived'; template:'standard'|'landing'|'full_width'; display_order:number; is_indexable:boolean };
type Block = { id:string; page_id:string; block_type:string; block_key:string; title:string|null; content:Record<string,unknown>; display_order:number; is_active:boolean; style:Record<string,unknown> };
const BLOCKS=['hero','rich_text','image','two_column','cards','cta','spacer','divider','quote','feature_grid'];
const DEFAULTS:Record<string,Record<string,unknown>>={
 hero:{heading:'',subheading:'',description:'',image_url:'',button_text:'',button_link:''},
 rich_text:{heading:'',body:''}, image:{image_url:'',alt:'',caption:''},
 two_column:{left_heading:'',left_body:'',left_image:'',right_heading:'',right_body:'',right_image:'',reverse:false},
 cards:{heading:'',items:[{title:'',text:'',image_url:''}]}, cta:{heading:'',body:'',button_text:'',button_link:''},
 spacer:{height:64}, divider:{}, quote:{quote:'',author:''}, feature_grid:{heading:'',items:[{title:'',text:''}]}
};

export default function AdminPages(){
 const [pages,setPages]=useState<Page[]>([]); const [page,setPage]=useState<Page|null>(null); const [blocks,setBlocks]=useState<Block[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const {toast}=useToast();
 const load=useCallback(async()=>{setLoading(true);try{const {data,error}=await supabase.from('site_pages').select('*').order('display_order').order('title');if(error)throw error;setPages((data??[]) as Page[]); if(page){const {data:b,error:be}=await supabase.from('site_page_blocks').select('*').eq('page_id',page.id).order('display_order');if(be)throw be;setBlocks((b??[]) as Block[]);}}catch(e){toast({title:'Unable to load pages',description:e instanceof Error?e.message:'Access denied',variant:'destructive'});}finally{setLoading(false)}},[page,toast]);
 useEffect(()=>{void load()},[load]);
 const open=async(p:Page)=>{setPage(p);const {data,error}=await supabase.from('site_page_blocks').select('*').eq('page_id',p.id).order('display_order');if(error){toast({title:'Unable to load blocks',variant:'destructive'});return}setBlocks((data??[]) as Block[])};
 const addPage=async()=>{const title='New Page';const slug=`new-page-${Date.now()}`;const {data,error}=await supabase.from('site_pages').insert({title,slug,status:'draft',template:'standard',display_order:pages.length}).select().single();if(error){toast({title:'Create page failed',description:error.message,variant:'destructive'});return}setPages(p=>[...p,data as Page]);setPage(data as Page);setBlocks([])};
 const savePage=async()=>{if(!page)return;setSaving(true);try{const {error}=await supabase.from('site_pages').update({slug:page.slug,title:page.title,seo_title:page.seo_title,seo_description:page.seo_description,status:page.status,template:page.template,is_indexable:page.is_indexable,updated_at:new Date().toISOString()}).eq('id',page.id);if(error)throw error;toast({title:'Page saved'});await load()}catch(e){toast({title:'Page save failed',description:e instanceof Error?e.message:'Unable to save',variant:'destructive'})}finally{setSaving(false)}};
 const addBlock=async(type:string)=>{if(!page)return;const {data,error}=await supabase.from('site_page_blocks').insert({page_id:page.id,block_type:type,block_key:`${type}-${Date.now()}`,title:type.replace('_',' '),content:DEFAULTS[type]||{},display_order:blocks.length,style:{}}).select().single();if(error){toast({title:'Add block failed',description:error.message,variant:'destructive'});return}setBlocks(b=>[...b,data as Block])};
 const saveBlock=async(b:Block)=>{setSaving(true);try{const {data,error}=await supabase.rpc('save_site_page_block',{p_block_id:b.id,p_page_id:b.page_id,p_block_type:b.block_type,p_block_key:b.block_key,p_title:b.title,p_content:b.content,p_display_order:b.display_order,p_is_active:b.is_active,p_style:b.style});if(error)throw error;setBlocks(bs=>bs.map(x=>x.id===b.id?{...b,id:String(data)}:x));toast({title:'Block saved'})}catch(e){toast({title:'Block save failed',description:e instanceof Error?e.message:'Unable to save',variant:'destructive'})}finally{setSaving(false)}};
 const deleteBlock=async(id:string)=>{if(!confirm('Delete this block?'))return;const {error}=await supabase.from('site_page_blocks').delete().eq('id',id);if(error){toast({title:'Delete failed',variant:'destructive'});return}setBlocks(b=>b.filter(x=>x.id!==id))};
 const move=async(i:number,d:-1|1)=>{const j=i+d;if(j<0||j>=blocks.length)return;const a=blocks[i],b=blocks[j];await Promise.all([supabase.from('site_page_blocks').update({display_order:b.display_order}).eq('id',a.id),supabase.from('site_page_blocks').update({display_order:a.display_order}).eq('id',b.id)]);setBlocks(bs=>{const n=[...bs];[n[i],n[j]]=[n[j],n[i]];return n.map((x,k)=>({...x,display_order:k}))})};
 const updateContent=(id:string,patch:Record<string,unknown>)=>setBlocks(bs=>bs.map(b=>b.id===id?{...b,content:{...b.content,...patch}}:b));
 if(loading&&!pages.length)return <AdminLayout title="No-Code Pages"><div className="py-16 text-center text-gray-500">Loading pages...</div></AdminLayout>;
 return <AdminLayout title="No-Code Pages" subtitle="Create new public pages from safe, structured blocks without writing React code.">
 <div className="grid lg:grid-cols-[280px_1fr] gap-6 max-w-7xl">
  <aside className="bg-white border rounded-xl p-4 h-fit"><button onClick={()=>void addPage()} className="btn-primary w-full mb-4"><Plus className="w-4 h-4 inline mr-2"/>New Page</button><div className="space-y-1">{pages.map(p=><button key={p.id} onClick={()=>void open(p)} className={`w-full text-left px-3 py-2 rounded-lg text-sm ${page?.id===p.id?'bg-primary-50 text-primary-700':'hover:bg-gray-50'}`}>{p.title}<span className="block text-xs text-gray-400">/{p.slug} · {p.status}</span></button>)}</div></aside>
  {!page?<div className="bg-white border rounded-xl p-10 text-center text-gray-500">Select a page or create a new one.</div>:<main className="space-y-5">
   <section className="bg-white border rounded-xl p-5 grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Page title<input value={page.title} onChange={e=>setPage({...page,title:e.target.value})} className="input mt-1"/></label><label className="text-sm font-medium">URL slug<input value={page.slug} onChange={e=>setPage({...page,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'-')})} className="input mt-1"/></label><label className="text-sm font-medium">Template<select value={page.template} onChange={e=>setPage({...page,template:e.target.value as Page['template']})} className="input mt-1"><option>standard</option><option>landing</option><option>full_width</option></select></label><label className="text-sm font-medium">Status<select value={page.status} onChange={e=>setPage({...page,status:e.target.value as Page['status']})} className="input mt-1"><option>draft</option><option>published</option><option>archived</option></select></label><label className="text-sm font-medium">SEO title<input value={page.seo_title||''} onChange={e=>setPage({...page,seo_title:e.target.value})} className="input mt-1"/></label><label className="text-sm font-medium">SEO description<input value={page.seo_description||''} onChange={e=>setPage({...page,seo_description:e.target.value})} className="input mt-1"/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={page.is_indexable} onChange={e=>setPage({...page,is_indexable:e.target.checked})}/>Index in search engines</label><div><button disabled={saving} onClick={()=>void savePage()} className="btn-primary"><Save className="w-4 h-4 inline mr-2"/>Save Page</button></div></section>
   <section className="bg-white border rounded-xl p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-semibold">Blocks</h2><p className="text-sm text-gray-500">Each block is responsive and styleable. Use the Design & CSS control plane for advanced visual changes.</p></div><select defaultValue="" onChange={e=>{if(e.target.value){void addBlock(e.target.value);e.currentTarget.value=''}}} className="input max-w-xs"><option value="">+ Add block...</option>{BLOCKS.map(x=><option key={x}>{x}</option>)}</select></div>
   <div className="space-y-4">{blocks.map((b,i)=><div key={b.id} className="border rounded-xl p-4"><div className="flex items-center gap-2 mb-3"><strong className="capitalize">{b.block_type.replace('_',' ')}</strong><span className="text-xs text-gray-400 ml-auto">#{i+1}</span><button onClick={()=>void move(i,-1)} disabled={i===0} className="p-1"><ArrowUp className="w-4 h-4"/></button><button onClick={()=>void move(i,1)} disabled={i===blocks.length-1} className="p-1"><ArrowDown className="w-4 h-4"/></button><button onClick={()=>void deleteBlock(b.id)} className="p-1 text-red-500"><Trash2 className="w-4 h-4"/></button></div><label className="block text-sm font-medium mb-3">Block title<input value={b.title||''} onChange={e=>setBlocks(bs=>bs.map(x=>x.id===b.id?{...x,title:e.target.value}:x))} className="input mt-1"/></label><textarea value={JSON.stringify(b.content,null,2)} onChange={e=>{try{updateContent(b.id,JSON.parse(e.target.value))}catch{/* invalid JSON while typing */}}} className="input font-mono text-xs min-h-[150px]"/><button disabled={saving} onClick={()=>void saveBlock(b)} className="btn-secondary mt-3"><Save className="w-4 h-4 inline mr-2"/>Save Block</button></div>)}</div></section>
  </main>}
 </div></AdminLayout>
}
