import { useEffect, useState } from 'react';
import { CheckCircle2, ClipboardList, AlertTriangle, PackageCheck, Plus, Save, ShieldCheck } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';
import { completeProjectWithSignoff, createProjectIssue, createProjectTask, recordProjectMeasurement, resolveProjectIssue, scheduleProjectInstallation, updateProjectProgress, updateProjectTask } from '@/lib/lifecycle';

type Project = { id:string; title:string; client_name:string|null; status:string; progress_percentage:number; project_value:number|null; customer_approval:boolean };
type Task = { id:string; project_id:string; title:string; status:string; due_date:string|null };
type Issue = { id:string; project_id:string; title:string; severity:string; status:string; description:string|null };
type Allocation = { id:string; project_id:string; quantity_allocated:number; product_id:string; warehouse_id:string; notes:string|null; created_at:string };

export default function AdminProjectDelivery() {
  const [projects,setProjects]=useState<Project[]>([]); const [tasks,setTasks]=useState<Task[]>([]); const [issues,setIssues]=useState<Issue[]>([]); const [allocations,setAllocations]=useState<Allocation[]>([]); const [selected,setSelected]=useState<string>('');
  const [progress,setProgress]=useState(0); const [measurementLabel,setMeasurementLabel]=useState(''); const [measurementValue,setMeasurementValue]=useState(''); const [measurementUnit,setMeasurementUnit]=useState('m²'); const [measurements,setMeasurements]=useState<any[]>([]); const [installationDate,setInstallationDate]=useState(''); const [taskTitle,setTaskTitle]=useState(''); const [issueTitle,setIssueTitle]=useState(''); const [issueSeverity,setIssueSeverity]=useState('medium'); const [saving,setSaving]=useState(false); const [customerName,setCustomerName]=useState(''); const [signature,setSignature]=useState(''); const {toast}=useToast();
  const load=async()=>{ const [{data:p},{data:t},{data:i},{data:a},{data:m}]=await Promise.all([supabase.from('projects').select('id,title,client_name,status,progress_percentage,project_value,customer_approval').order('created_at',{ascending:false}),supabase.from('project_tasks').select('*').order('display_order'),supabase.from('project_issues').select('*').order('created_at',{ascending:false}),supabase.from('project_material_allocations').select('*').order('created_at',{ascending:false}),supabase.from('project_measurements').select('*').order('recorded_at',{ascending:false})]); setProjects((p||[]) as Project[]); setTasks((t||[]) as Task[]); setIssues((i||[]) as Issue[]); setAllocations((a||[]) as Allocation[]); setMeasurements((m||[]) as any[]); if(!selected && p?.[0]) {setSelected(p[0].id);setProgress(p[0].progress_percentage||0);} };
  useEffect(()=>{load();},[]);
  const projectMeasurements=measurements.filter(m=>m.project_id===selected); const current=projects.find(p=>p.id===selected); const projectTasks=tasks.filter(t=>t.project_id===selected); const projectIssues=issues.filter(i=>i.project_id===selected); const projectAllocations=allocations.filter(a=>a.project_id===selected);
  const run=async(fn:()=>Promise<any>,success:string)=>{setSaving(true);try{const r=await fn();if(r?.success===false)throw new Error(r.error);toast({title:success});await load();}catch(e){toast({title:'Operation failed',description:e instanceof Error?e.message:'Unknown error',variant:'destructive'});}finally{setSaving(false);}};
  return <AdminLayout title="Project Delivery & Field Operations"><div className="space-y-6">
    <div className="grid xl:grid-cols-[330px_1fr] gap-6">
      <section className="bg-white border rounded-xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold text-lg text-navy-900">Active Projects</h2><p className="text-sm text-gray-500">Run execution from one operational view.</p></div><div className="divide-y max-h-[620px] overflow-auto">{projects.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setProgress(p.progress_percentage||0)}} className={`w-full text-left p-4 hover:bg-gray-50 ${selected===p.id?'bg-gray-50 border-l-4 border-primary-600':''}`}><div className="font-semibold">{p.title}</div><div className="text-xs text-gray-500 mt-1">{p.client_name||'No customer'} · {p.status}</div><div className="mt-3 h-2 bg-gray-100 rounded-full"><div className="h-2 rounded-full bg-primary-600" style={{width:`${p.progress_percentage||0}%`}}/></div><div className="text-xs mt-1 text-gray-500">{p.progress_percentage||0}% complete</div></button>)}</div></section>
      <section className="space-y-6">{!current?<div className="bg-white border rounded-xl p-10 text-center text-gray-500">No project available.</div>:<>
        <div className="bg-white border rounded-xl p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-bold text-navy-900">{current.title}</h2><p className="text-sm text-gray-500">{current.client_name||'Customer not linked'} · {current.status}</p></div><span className="px-3 py-1 rounded-full text-xs font-bold bg-gray-100">{current.customer_approval?'Customer approved':'Awaiting sign-off'}</span></div><div className="mt-5 grid md:grid-cols-[1fr_auto] gap-3"><input type="range" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/><button disabled={saving} className="btn-primary flex items-center gap-2" onClick={()=>run(()=>updateProjectProgress(current.id,progress), 'Project progress updated')}><Save className="w-4 h-4"/>Save Progress</button></div><div className="text-sm text-gray-500 mt-2">{progress}% execution progress</div></div>
        <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5 lg:col-span-2"><h3 className="font-bold">Installation Scheduling</h3><div className="flex flex-wrap gap-3 mt-4"><input className="input" type="date" value={installationDate} onChange={e=>setInstallationDate(e.target.value)}/><button disabled={!installationDate||saving} className="btn-primary" onClick={()=>run(async()=>{const r=await scheduleProjectInstallation(current.id,null,installationDate);setInstallationDate('');return r},'Installation scheduled')}>Schedule Installation</button></div></section>
          <section className="bg-white border rounded-xl p-5"><h3 className="font-bold flex items-center gap-2"><ClipboardList className="w-4 h-4"/>Delivery Tasks</h3><div className="flex gap-2 mt-4"><input className="input flex-1" placeholder="Task title" value={taskTitle} onChange={e=>setTaskTitle(e.target.value)}/><button disabled={!taskTitle||saving} className="btn-primary" onClick={()=>run(async()=>{const id=await createProjectTask(current.id,taskTitle);setTaskTitle('');return {success:!!id}},'Task added')}><Plus className="w-4 h-4"/></button></div><div className="mt-4 space-y-2">{projectTasks.map(t=><div key={t.id} className="flex items-center justify-between gap-3 border rounded-lg p-3"><span className={t.status==='completed'?'line-through text-gray-400':''}>{t.title}</span>{t.status!=='completed'&&<button onClick={()=>run(()=>updateProjectTask(t.id,'completed'),'Task completed')} className="text-green-700"><CheckCircle2 className="w-5 h-5"/></button>}</div>)}{projectTasks.length===0&&<p className="text-sm text-gray-500">No delivery tasks yet.</p>}</div></section>
          <section className="bg-white border rounded-xl p-5"><h3 className="font-bold flex items-center gap-2"><AlertTriangle className="w-4 h-4"/>Issues & Exceptions</h3><div className="flex gap-2 mt-4"><input className="input flex-1" placeholder="Issue title" value={issueTitle} onChange={e=>setIssueTitle(e.target.value)}/><select className="input w-28" value={issueSeverity} onChange={e=>setIssueSeverity(e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><button disabled={!issueTitle||saving} className="btn-primary" onClick={()=>run(async()=>{const id=await createProjectIssue(current.id,issueTitle,undefined,issueSeverity);setIssueTitle('');return {success:!!id}},'Issue logged')}><Plus className="w-4 h-4"/></button></div><div className="mt-4 space-y-2">{projectIssues.map(i=><div key={i.id} className="border rounded-lg p-3 flex items-center justify-between"><div><div className="font-medium">{i.title}</div><div className="text-xs text-gray-500">{i.severity} · {i.status}</div></div>{i.status!=='resolved'&&<button onClick={()=>run(()=>resolveProjectIssue(i.id,'resolved'),'Issue resolved')} className="text-green-700"><CheckCircle2 className="w-5 h-5"/></button>}</div>)}{projectIssues.length===0&&<p className="text-sm text-gray-500">No open issues.</p>}</div></section>
        </div>
        <div className="grid lg:grid-cols-2 gap-6"><section className="bg-white border rounded-xl p-5 lg:col-span-2"><h3 className="font-bold">Site Measurements</h3><div className="flex flex-wrap gap-2 mt-4"><input className="input" placeholder="Measurement label" value={measurementLabel} onChange={e=>setMeasurementLabel(e.target.value)}/><input className="input w-28" type="number" min="0" step="0.001" placeholder="Value" value={measurementValue} onChange={e=>setMeasurementValue(e.target.value)}/><input className="input w-24" value={measurementUnit} onChange={e=>setMeasurementUnit(e.target.value)}/><button disabled={!measurementLabel||!measurementValue||saving} className="btn-primary" onClick={()=>run(async()=>{const id=await recordProjectMeasurement(current.id,measurementLabel,Number(measurementValue),measurementUnit);setMeasurementLabel('');setMeasurementValue('');return {success:!!id}},'Measurement recorded')}>Record</button></div><div className="flex flex-wrap gap-2 mt-4">{projectMeasurements.map(m=><span key={m.id} className="px-3 py-1.5 rounded-lg bg-gray-50 border text-sm">{m.label}: {m.value} {m.unit}</span>)}</div></section><section className="bg-white border rounded-xl p-5"><h3 className="font-bold flex items-center gap-2"><PackageCheck className="w-4 h-4"/>Material Allocations</h3><p className="text-sm text-gray-500 mt-2">Stock allocated through the transactional inventory engine.</p><div className="mt-4 space-y-2">{projectAllocations.map(a=><div key={a.id} className="border rounded-lg p-3 text-sm">{a.quantity_allocated} units · Product {a.product_id.slice(0,8)} · Warehouse {a.warehouse_id.slice(0,8)}</div>)}{projectAllocations.length===0&&<p className="text-sm text-gray-500">No materials allocated.</p>}</div></section>
        <section className="bg-white border rounded-xl p-5"><h3 className="font-bold flex items-center gap-2"><ShieldCheck className="w-4 h-4"/>Customer Completion Sign-off</h3><div className="grid gap-3 mt-4"><input className="input" placeholder="Customer name" value={customerName} onChange={e=>setCustomerName(e.target.value)}/><input className="input" placeholder="Signature / confirmation reference" value={signature} onChange={e=>setSignature(e.target.value)}/><textarea className="input" placeholder="Completion notes"/><button disabled={saving||!customerName||!signature} className="btn-primary" onClick={()=>run(()=>completeProjectWithSignoff(current.id,true,customerName,signature),'Project completed and signed off')}><CheckCircle2 className="w-4 h-4 mr-2 inline"/>Complete Project</button></div></section></div>
      </>}</section>
    </div></div></AdminLayout>;
}
