import {useCallback,useEffect,useState} from 'react';
import {AlertTriangle,CheckCircle2,ClipboardCheck,RefreshCw} from 'lucide-react';
import {AdminLayout} from './dashboard';
import {createQualityCorrectiveAction360,createQualityInspection360,getQualityAssurance360,updateQualityCorrectiveAction360,type QualitySnapshot} from '@/lib/quality-assurance-360';
const val=(x:unknown)=>String(x??'—');
export default function QualityAssurance360(){const [data,setData]=useState<QualitySnapshot|null>(null);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const load=useCallback(async()=>{setLoading(true);try{setData(await getQualityAssurance360());setMessage('')}catch(e){setMessage(e instanceof Error?e.message:'Unable to load quality controls.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
const newInspection=async()=>{const title=window.prompt('Inspection title');if(!title?.trim())return;const type=window.prompt('Reference type: project, supplier, delivery, service_case, maintenance, warehouse, other','project')||'project';try{await createQualityInspection360({referenceType:type,title});setMessage('Inspection created.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create inspection.')}};
const newAction=async(i:string)=>{const finding=window.prompt('Finding');if(!finding?.trim())return;const plan=window.prompt('Corrective action plan (minimum 10 characters)');if(!plan?.trim())return;const severity=window.prompt('Severity: low, medium, high, critical','medium')||'medium';try{await createQualityCorrectiveAction360({inspectionId:i,finding,severity,actionPlan:plan});setMessage('Corrective action created.');await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create corrective action.')}};
const advance=async(a:Record<string,unknown>)=>{const status=String(a.status);const next=status==='open'?'in_progress':status==='in_progress'?'completed':status==='completed'?'verified':'closed';const notes=next==='verified'||next==='closed'?window.prompt('Verification notes (minimum 10 characters)'):undefined;if((next==='verified'||next==='closed')&&!notes?.trim())return;try{await updateQualityCorrectiveAction360(val(a.id),next,notes ?? undefined);setMessage(`Corrective action ${next}.`);await load()}catch(e){setMessage(e instanceof Error?e.message:'Unable to update corrective action.')}};
const m=data?.metrics||{};return <AdminLayout title="Quality Assurance & Corrective Action 360" subtitle="Inspection outcomes, nonconformances and verified corrective actions across operations." actions={<button onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className={loading?'h-4 w-4 animate-spin':'h-4 w-4'}/>Refresh</button>}>
{message&&<div className="mb-5 rounded-xl border bg-white p-4 text-sm">{message}</div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6">{[['Inspections',m.inspections_total],['Open inspections',m.open_inspections],['Failed',m.failed_inspections],['Open actions',m.open_actions],['Overdue',m.overdue_actions],['Critical',m.critical_actions]].map(([l,v])=><div key={String(l)} className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">{String(l)}</p><p className="mt-1 text-3xl font-semibold">{loading?'—':Number(v||0)}</p></div>)}</div>
<div className="mt-6 flex justify-end"><button onClick={()=>void newInspection()} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">New inspection</button></div>
<section className="mt-4 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Inspection register</h2><p className="text-sm text-muted-foreground">Quality outcomes remain visible across projects and service operations.</p></div></div><div className="mt-5 space-y-3">{data?.inspections.map(i=><div key={val(i.id)} className="rounded-xl border p-4 flex flex-wrap justify-between gap-3"><div><p className="font-medium">{val(i.title)}</p><p className="text-sm text-muted-foreground">{val(i.reference_type)} · {val(i.status)} · score {val(i.score)}</p>{i.findings_summary != null && <p className="mt-1 text-sm">{val(i.findings_summary)}</p>}</div><button onClick={()=>void newAction(val(i.id))} disabled={['closed','waived'].includes(val(i.status))} className="rounded-lg border px-3 py-2 text-sm">Add finding</button></div>)}</div></section>
<section className="mt-6 rounded-2xl border bg-card p-6"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">Corrective actions</h2><p className="text-sm text-muted-foreground">Progression requires verification evidence before closure.</p></div></div><div className="mt-5 space-y-3">{data?.actions.length?data.actions.map(a=><div key={val(a.id)} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-medium">{val(a.inspection_title)} · {val(a.severity)}</p><p className="mt-1 text-sm">{val(a.finding)}</p><p className="text-sm text-muted-foreground">{val(a.status)} · due {a.due_at?new Date(String(a.due_at)).toLocaleString():'not set'}</p></div><button onClick={()=>void advance(a)} className="rounded-lg border px-3 py-2 text-sm">Advance</button></div></div>):<div className="flex items-center gap-2 py-6 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4"/>No open corrective actions.</div>}</div></section>
</AdminLayout>}
