import { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from './dashboard';
import { useToast } from '@/hooks/use-toast';
import { CalendarDays, CheckCircle2, Clock3, ShieldCheck, Wrench, AlertTriangle } from 'lucide-react';
import { getServiceCaseOperations360, transitionServiceCase360 } from '@/lib/service-cases-360';
import { getServiceCaseQuality360, reconcileServiceCaseSlas360, refreshServiceCaseWarranty360 } from '@/lib/service-quality-360';

type CaseRow={id:string;case_number:string;customer_name?:string|null;customer_phone?:string|null;customer_email?:string|null;issue_title?:string|null;description?:string|null;priority?:string|null;sla_due_at?:string|null;type?:string|null;warranty_valid?:boolean|null;status:string;assigned_to?:string|null;[key:string]:unknown};

export default function AdminServiceCases(){
  const [cases,setCases]=useState<CaseRow[]>([]); const [metrics,setMetrics]=useState<Record<string,number>>({}); const [quality,setQuality]=useState<Record<string,number>>({}); const [loading,setLoading]=useState(true); const [reconciling,setReconciling]=useState(false); const {toast}=useToast();
  const load=useCallback(async()=>{setLoading(true);try{const [data,qualityData]=await Promise.all([getServiceCaseOperations360(),getServiceCaseQuality360()]);setCases(data.cases||[]);setMetrics(data.metrics||{});setQuality(qualityData.metrics||{})}catch(e){toast({title:'Unable to load service operations',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}finally{setLoading(false)}},[toast]);
  useEffect(()=>{void load()},[load]);
  const reconcile=async()=>{setReconciling(true);try{const result=await reconcileServiceCaseSlas360();toast({title:'SLA reconciliation complete',description:`${result.updated_cases||0} case(s) escalated or de-escalated.`});await load()}catch(e){toast({title:'SLA reconciliation failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}finally{setReconciling(false)}};
  const validateWarranty=async(c:CaseRow)=>{try{const result=await refreshServiceCaseWarranty360(c.id);toast({title:'Warranty entitlement checked',description:result.warranty_valid?'Active warranty validated.':'Active warranty could not be validated.'});await load()}catch(e){toast({title:'Warranty validation failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}};
  const run=async(c:CaseRow,status:string)=>{try{await transitionServiceCase360({id:c.id,status,assignedTo:c.assigned_to||null,resolution:status==='resolved'?'Resolved through service operations':null});toast({title:`${c.case_number} moved to ${status.replace('_',' ')}`});await load()}catch(e){toast({title:'Lifecycle update failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}};
  return <AdminLayout title="Warranty & Service" subtitle="SLA-aware after-sales operations with a complete case lifecycle and audit trail.">
    <div className="flex flex-wrap items-center justify-between gap-3 mb-5"><div><p className="eyebrow">Quality & entitlement</p><p className="text-sm text-muted-foreground">Reconcile SLA escalation and validate warranty coverage before field action.</p></div><button className="btn-secondary" onClick={reconcile} disabled={reconciling}>{reconciling?'Reconciling…':'Reconcile SLAs'}</button></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-6"><div className="surface p-5"><p className="eyebrow">Avg. rating</p><p className="text-2xl font-bold mt-2">{Number(quality.average_rating||0).toFixed(2)} / 5</p><p className="text-xs text-muted-foreground mt-1">{quality.feedback_count||0} responses</p></div><div className="surface p-5"><p className="eyebrow">Low ratings</p><p className="text-2xl font-bold mt-2">{quality.low_rating_count||0}</p></div><div className="surface p-5"><p className="eyebrow">Warranty verified</p><p className="text-2xl font-bold mt-2">{quality.warranty_valid||0}</p></div><div className="surface p-5"><p className="eyebrow">Escalated open</p><p className="text-2xl font-bold mt-2">{quality.escalated_open||0}</p></div></div>
    <div className="grid gap-4 sm:grid-cols-6 mb-6">{([['Open','open',Clock3],['Review','in_review',ShieldCheck],['Scheduled','scheduled',CalendarDays],['In progress','in_progress',Wrench],['Overdue','overdue',AlertTriangle],['Critical','critical',AlertTriangle]] as const).map(([label,key,Icon])=><div className="surface p-5" key={key}><p className="eyebrow">{label}</p><p className="text-2xl font-bold mt-2">{metrics[key]??0}</p><Icon className="w-4 h-4 mt-2 opacity-60"/></div>)}</div>
    <div className="table-shell overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Case</th><th>Customer</th><th>Issue</th><th>Priority</th><th>SLA</th><th>Warranty</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={8} className="p-8 text-center">Loading…</td></tr>:cases.map(c=><tr key={c.id}><td className="font-mono text-sm">{c.case_number}</td><td>{c.customer_name||'—'}<div className="text-xs text-muted-foreground">{c.customer_phone||c.customer_email||''}</div></td><td><div className="font-medium">{c.issue_title}</div><div className="text-xs text-muted-foreground max-w-xs truncate">{c.description}</div></td><td><span className="chip">{c.priority}</span></td><td className={c.sla_due_at&&new Date(c.sla_due_at)<new Date()&&!['resolved','closed','rejected'].includes(c.status)?'font-semibold':''}>{c.sla_due_at?new Date(c.sla_due_at).toLocaleString():'—'}</td><td>{c.type==='warranty'?<button className="text-xs underline" onClick={()=>validateWarranty(c)}>{c.warranty_valid===true?'Verified':c.warranty_valid===false?'Not covered':'Check coverage'}</button>:'—'}</td><td><span className="chip">{c.status}</span></td><td className="flex gap-2 py-3">{c.status==='open'&&<button className="btn-secondary" onClick={()=>run(c,'in_review')}>Review</button>}{['open','in_review'].includes(c.status)&&<button className="btn-primary" onClick={()=>run(c,'scheduled')}><CalendarDays className="w-4 h-4"/></button>}{c.status==='scheduled'&&<button className="btn-primary" onClick={()=>run(c,'in_progress')}><Wrench className="w-4 h-4"/></button>}{c.status==='in_progress'&&<button className="btn-primary" onClick={()=>run(c,'resolved')}><CheckCircle2 className="w-4 h-4"/></button>}{c.status==='resolved'&&<button className="btn-secondary" onClick={()=>run(c,'closed')}>Close</button>}</td></tr>)}{!loading&&!cases.length&&<tr><td colSpan={8} className="p-10 text-center text-muted-foreground"><ShieldCheck className="w-10 h-10 mx-auto mb-3 opacity-50"/>No warranty or service cases yet.</td></tr>}</tbody></table></div></div>
  </AdminLayout>
}
