import { useCallback, useEffect, useState } from 'react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { updateServiceCase } from '@/lib/service-cases';
import { useToast } from '@/hooks/use-toast';
import { ShieldCheck, Wrench, CalendarDays, CheckCircle2 } from 'lucide-react';

type ServiceCase = { id:string; case_number:string; type:string; issue_title:string; description?:string|null; priority:string; status:string; customer?:{name?:string|null;email?:string|null;phone?:string|null}|null; project?:{title?:string|null}|null; order?:{order_number?:string|null}|null };

export default function AdminServiceCases(){const [cases,setCases]=useState<ServiceCase[]>([]);const [loading,setLoading]=useState(true);const {toast}=useToast();const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('service_cases').select('*, customer:customers(name,email,phone), project:projects(title), order:orders(order_number)').order('created_at',{ascending:false});if(error)toast({title:'Unable to load service cases',description:error.message,variant:'destructive'});setCases((data||[]) as ServiceCase[]);setLoading(false)},[toast]);useEffect(()=>{void load()},[load]);const run=async(id:string,status:string)=>{try{await updateServiceCase({id,status});toast({title:`Case moved to ${status}`});await load()}catch(e){toast({title:'Update failed',description:e instanceof Error?e.message:'Please try again',variant:'destructive'})}};return <AdminLayout title="Warranty & Service" subtitle="Manage warranty claims, maintenance requests and after-sales service through one lifecycle."><div className="grid gap-4 sm:grid-cols-4 mb-6">{['open','in_review','scheduled','resolved'].map(s=><div className="surface p-5" key={s}><p className="eyebrow">{s.replace('_',' ')}</p><p className="text-2xl font-bold mt-2">{cases.filter(c=>c.status===s).length}</p></div>)}</div><div className="table-shell overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th>Case</th><th>Customer</th><th>Type</th><th>Issue</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-8 text-center">Loading…</td></tr>:cases.map(c=><tr key={c.id}><td className="font-mono text-sm">{c.case_number}</td><td>{c.customer?.name||'—'}<div className="text-xs text-muted-foreground">{c.customer?.phone||c.customer?.email||''}</div></td><td><span className="chip">{c.type}</span></td><td><div className="font-medium">{c.issue_title}</div><div className="text-xs text-muted-foreground max-w-xs truncate">{c.description}</div></td><td>{c.priority}</td><td><span className="chip">{c.status}</span></td><td className="flex gap-2 py-3">{c.status==='open'&&<button className="btn-secondary" onClick={()=>run(c.id,'in_review')}>Review</button>}{['open','in_review'].includes(c.status)&&<button className="btn-primary" onClick={()=>run(c.id,'scheduled')}><CalendarDays className="w-4 h-4"/></button>}{c.status==='scheduled'&&<button className="btn-primary" onClick={()=>run(c.id,'in_progress')}><Wrench className="w-4 h-4"/></button>}{c.status==='in_progress'&&<button className="btn-primary" onClick={()=>run(c.id,'resolved')}><CheckCircle2 className="w-4 h-4"/></button>}</td></tr>)}{!loading&&!cases.length&&<tr><td colSpan={7} className="p-10 text-center text-muted-foreground"><ShieldCheck className="w-10 h-10 mx-auto mb-3 opacity-50"/>No warranty or service cases yet.</td></tr>}</tbody></table></div></div></AdminLayout>}
