import { useCallback, useEffect, useState } from 'react';
import { Plus, Save, Trash2 } from 'lucide-react';
import { AdminLayout } from './dashboard';
import { supabase } from '@/lib/supabase';
import { useToast } from '@/hooks/use-toast';

type Row={id:string;route:string;content_key:string;value:Record<string,unknown>;description:string|null;is_active:boolean};
export default function AdminSiteContent(){
 const [rows,setRows]=useState<Row[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const {toast}=useToast();
 const load=useCallback(async()=>{setLoading(true);const {data,error}=await supabase.from('site_content_registry').select('*').order('route').order('content_key');if(error)toast({title:'Unable to load public content',description:error.message,variant:'destructive'});else setRows((data??[]) as Row[]);setLoading(false)},[toast]);
 useEffect(()=>{void load()},[load]);
 const add=()=>setRows(r=>[...r,{id:`new-${Date.now()}`,route:'/',content_key:'new.key',value:{text:''},description:'',is_active:true}]);
 const save=async(row:Row)=>{setSaving(true);const payload={route:row.route.toLowerCase().trim()||'/',content_key:row.content_key.trim(),value:row.value,description:row.description,is_active:row.is_active,updated_at:new Date().toISOString()};const result=row.id.startsWith('new-')?await supabase.from('site_content_registry').insert(payload).select().single():await supabase.from('site_content_registry').update(payload).eq('id',row.id).select().single();if(result.error)toast({title:'Save failed',description:result.error.message,variant:'destructive'});else {toast({title:'Content override saved'});await load()}setSaving(false)};
 const remove=async(row:Row)=>{if(row.id.startsWith('new-')){setRows(r=>r.filter(x=>x.id!==row.id));return}if(!confirm('Delete this content override?'))return;const {error}=await supabase.from('site_content_registry').delete().eq('id',row.id);if(error)toast({title:'Delete failed',description:error.message,variant:'destructive'});else await load()};
 return <AdminLayout title="Public Content Control" subtitle="Override public-site copy and content by route without changing React code. Existing hard-coded defaults remain safe fallbacks until an override is supplied."><div className="max-w-7xl space-y-4"><div className="flex justify-end"><button onClick={add} className="btn-primary"><Plus className="w-4 h-4 inline mr-2"/>Add Override</button></div>{loading?<div className="py-12 text-center text-gray-500">Loading content registry...</div>:rows.map(row=><div key={row.id} className="bg-white border rounded-xl p-4 grid lg:grid-cols-[160px_180px_1fr_120px_auto] gap-3 items-start"><input className="input" value={row.route} onChange={e=>setRows(r=>r.map(x=>x.id===row.id?{...x,route:e.target.value}:x))} placeholder="/contact"/><input className="input" value={row.content_key} onChange={e=>setRows(r=>r.map(x=>x.id===row.id?{...x,content_key:e.target.value}:x))} placeholder="hero.title"/><textarea className="input font-mono text-xs min-h-[90px]" value={JSON.stringify(row.value,null,2)} onChange={e=>{try{const value=JSON.parse(e.target.value);setRows(r=>r.map(x=>x.id===row.id?{...x,value}:x))}catch { /* Keep the last valid value until JSON is valid. */}}}/><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={row.is_active} onChange={e=>setRows(r=>r.map(x=>x.id===row.id?{...x,is_active:e.target.checked}:x))}/>Active</label><div className="flex gap-2"><button disabled={saving} onClick={()=>void save(row)} className="btn-secondary"><Save className="w-4 h-4"/></button><button onClick={()=>void remove(row)} className="p-2 text-red-500"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></AdminLayout>
}
